### ISSUE TITLE
CardPage and CardSlideTransition are broken

### ISSUE THREAD

**Issue by ricardomv** [papyros/qml-material#101]
CardPage still uses deprecated IconAction
property transition can't be set on a Page
theme.blackColor('secondary') is deprecated??
and others

I don't know what CardPage is supposed to do so i can't fix this.

**Comment by iBeliever** [comment]
The CardPage and all the transitions were broken by the switch to QtQuick.Controls. This is what the card page is:

![Card page](https://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0Bx4BSt6jniD7bW1TYXlMT0JxUWM/layout_structure_toolbars4.png)

I'm going to leave this as targetted for  Version 0.1, but I don't think it's critical for the first version, so let's just delete the broken components and revisit it in the next version.
