### ISSUE TITLE
Toolbar and tabbar disappear.

### ISSUE THREAD

**Issue by cccco** [papyros/qml-material#109]
Hi papyros!

I downloaded the latest version of the demo application and then launched it. Then I clicked "Page Stack" button on right sidebar and "Push Subpage" button too. The page "Page Title" was opened. Then I clicked "Back" button. Once the main window was opened, toolbar was disappeared.

I use qml-material in my project. TabBar disappears as the toolbar when we are returning on the previous page.

Sorry for my poor english!

Dmitri.

**Comment by jneidlinger** [comment]
Hey Dmitri. I have a pull request that fixes that issue

https://github.com/papyros/qml-material/pull/108

As soon as the maintainers review and pull in the changes that will be fixed.

Thanks!

**Comment by iBeliever** [comment]
Closed by #108.
