### ISSUE TITLE
Checkbox animation bug when clicking on the label

### ISSUE THREAD

**Issue by Imote** [papyros/qml-material#111]
Hello :)
When we click on the label of the checkbox, the checkbox state is switched. But there is not the wave who is going out of the checkbox (this wave is present when we click on the checkbox) !
I don't know if it's normal or not ;)

Sorry for my poor english i hope you've understood

**Comment by jneidlinger** [comment]
That is intentional, and is how Google does the checkboxes. The ink only activates/animates when pressing the checkbox itself.

For example: https://www.polymer-project.org/components/paper-elements/demo.html#paper-checkbox

**Comment by Imote** [comment]
haha okay :p
i'm sorry :)
