### ISSUE TITLE
Dialog.show() don't work with QQmlApplicationEngine

### ISSUE THREAD

**Issue by bmeric** [papyros/qml-material#113]
Dialogs works fine with qmlscene but i can't get it working with QQmlApplicationEngine.

When i call actionableDialog.show() method, i get; "...qml/Material/Popover.qml:40: TypeError: Cannot call method 'mapToItem' of null".

**Comment by jneidlinger** [comment]
Your root QML object must be our "Material" ApplicationWindow, not the standard Quick Controls Application Window.

https://github.com/papyros/qml-material/blob/develop/modules/Material/ApplicationWindow.qml

**Comment by bmeric** [comment]
Oops, yes, you're right. Thanks.
