### ISSUE TITLE
 There is problem with icons on Android.

### ISSUE THREAD

**Issue by cccco** [papyros/qml-material#121]
Hi, papyros!

I have a problem with icons on Android:

> file:///data/data/com.mydomain.myapplication/qt-reserved-files/qml/Material/Icon.qml:40 ((null)): file:///data/data/com.mydomain.myapplication/qt-reserved-files/qml/Material/Icon.qml:40:5: QML Image: Invalid image data: file:///data/data/com.mydomain.myapplication/qt-reserved-files/qml/Material/icons/navigation/arrow_back.svg

Also for icons: more_vert.svg, close.svg (I see that in log). And also for iOS.

The icon arrow_back.svg is not shown.

I use only arrow_back.svg (at subpage) but problem is for all above icons.

There are not problems on desktop (Ubuntu, MacOS).

Dmitri.

**Comment by jneidlinger** [comment]
Sounds like you aren't including the QT svg module.
QT += svg
QTPLUGIN += qsvg

**Comment by cccco** [comment]
Thank you, jneidlinger!

You guided me on the right path. 

> QT += svg

We need to add in .pro file the module svg and also all its dependencies: widgets, gui, core. The program does not work properly without each of these modules.

> QTPLUGIN += qsvg

Add that in the .pro file does not necessary. Moreover, with this line in .pro file program is not working.

Dmitri.

**Comment by glenfordwilliams** [comment]
what does your .pro file look like?

**Comment by cccco** [comment]
My .pro file:

> TEMPLATE = app

> QT += qml quick widgets gui core svg

> SOURCES += ...

> RESOURCES += qml.qrc

> \# Additional import path used to resolve QML modules in Qt Creator's code model
> QML_IMPORT_PATH = /home/opt/Qt/5.4/android_armv7/qml/Material/

> \# Default rules for deployment.
> include(deployment.pri)

> HEADERS += ...

> DISTFILES += \
>     android/AndroidManifest.xml \
>     android/res/values/libs.xml \
>     android/build.gradle

> ANDROID_PACKAGE_SOURCE_DIR = $$PWD/android

**Comment by jneidlinger** [comment]
If its all figured out, please go ahead and close your issue :)

**Comment by ayberkozgur** [comment]
I have 
```
QT += qml quick bluetooth xml  widgets gui core svg

QTPLUGIN += qsvg
```
and I'm still getting this issue.

**Comment by marco-piccolino** [comment]
@ayberkozgur try deleting the build directory and the package on the device, I found it helps

**Comment by marco-piccolino** [comment]
@ayberkozgur btw there should be no need for the QTPLUGIN line

**Comment by ayberkozgur** [comment]
Thanks, deleting the build directory really did do the trick.

**Comment by vectorate** [comment]
Hello. I'm trying to use qml-material on my android app but for some reason, I can't figure out how to load qml-material as a library or plugin because everytime I try to run it, it complains about the inclusion of qml-material in that it caan't find it, can anyone please assit.

**Comment by marco-piccolino** [comment]
@vectorate hello there.
Make sure that you use Qt's android-specific `qmake` and `sudo make install`.
If you need further assistance please open a separate bug or come over to the gitter chat:
https://gitter.im/papyros/qml-material
