### ISSUE TITLE
Add avatar/image component to ListItem [$5]

### ISSUE THREAD

**Issue by marco-piccolino** [papyros/qml-material#123]

**Comment by ricardomv** [comment]
Currently this can be done by setting the action property to a Image type for example
```
ListItem.Standard {
    text: "Standard list item"
    action: CircleImage {
        anchors.fill: parent
        source: "/path/to/image"
    }
}
```
but please keep in mind this is not documented and can be changed in the future

**Comment by marco-piccolino** [comment]
Awesome - please keep me posted if this gets a stable API.
Keep in mind that in MD action (or better "primary action") refers to the whole content of the tile, and secondary action to the secondary icon/picture

**Comment by marco-piccolino** [comment]
ps feel free to claim the bounty and have a beer on me

**Comment by ricardomv** [comment]
Thank you very much for the donation, maybe i will post another bounty or if @iBeliever wants i will donate it for the expenses with the site. :+1:
