### ISSUE TITLE
MenuField height binding loop

### ISSUE THREAD

**Issue by MaxMansfield** [papyros/qml-material#125]
#### The file `/modules/Material/MenuField.qml` has a looping height binding issue

In the Dropdown class  in  `/modules/Material/MenuField.qml` there are is a parent height that refers to its child while its child refers to its parents height. This causes binding errors when building.

```QML
  Dropdown {
            id: menu

            anchor: Item.TopLeft

            width: spinBox.width

             // This line is the culprit and causes errors.  
            height: Math.min(maxVisibleItems*units.dp(48) + units.dp(24), listView.contentHeight)

            ListView {
                id: listView

                width: menu.width
                height: menu.height

                interactive: true

                delegate: Standard {
                    id: delegateItem

                    text: modelData

                    onClicked: {
                        itemSelected(index)
                        listView.currentIndex = index
                        menu.close()
                    }
                }
            }

```

Maybe a good solution would be to use 
```QML
height: maxVisibleItems*units.dp(48) + units.dp(24)
```
Instead of 
```QML
height: Math.min(maxVisibleItems*units.dp(48) + units.dp(24), listView.contentHeight)
```
on `line 97` of  `/modules/Material/MenuField.qml` 

I've been using that alternative and haven't noticed any effects.

**Comment by glenfordwilliams** [comment]
please submit a working patch. thanks

**Comment by MaxMansfield** [comment]
Okay I sent it to mspencer@sonrisesoftware.com because that's the only email I could find.

**Comment by ricardomv** [comment]
@MaxMansfield you can send a Pull Request here in Github. But the solution you provided doesn't quite work because if the number of items in the menu is less than the maxVisibleItems the dropdown does not resize properly.

**Comment by MaxMansfield** [comment]
Well @glenfordwilliams said to submit a patch not a pull request so I was following instructions. 

The entire reason I submitted this as an issue was because I wasn't trying to dig through code and provide a patch. I was trying to tell the developers to fix the error and provided a guess at the solution. In fact I've barely looked at the source for qml-material so I'm not the best to do it.

I posted the file,line and directions yet no one with commit access and knowledge of the project has stepped in to rework this?

The project is awesome and I would love to help but I'm swamped, otherwise I probably would have created a fork for pull requests.

**Comment by ricardomv** [comment]
@MaxMansfield i have looked into it before but i couldn't find any easy fix but this does not have any visual impact it just displays a warning in the console so it's not a priority right now. But thanks for taking the time to look into it.

**Comment by MaxMansfield** [comment]
@ricardomv Okay thanks for the info! Like I said when I get some time I'd love to help with the project so I may take a solid look at the code myself.
