### ISSUE TITLE
Documentation does not build [$5]

### ISSUE THREAD

**Issue by ricardomv** [papyros/qml-material#128]
When building documentation it hangs generating the docs for ApplicationWindow.qml using up all the RAM in the machine, the only clue that i have found about this issue is that it happens with all the components that inherit something from QtQuick Controls.

**Comment by iBeliever** [comment]
I filed an upstream bug for qdoc: https://bugreports.qt.io/browse/QTBUG-45680

**Comment by iBeliever** [comment]
Upstream bug is still open, but we're now building the documentation into xml and rendering that xml into nice Material Design HTML via [papyros/docmaker](https://github.com/papyros/docmaker) and publishing to GitHub pages on http://papyros.io/qml-material.
