### ISSUE TITLE
Scalable ui

### ISSUE THREAD

**Issue by dridk** [papyros/qml-material#134]
i wonder if you support scalability..
see http://www.kdab.com/scalable-uis-qml/

do you ?

**Comment by iBeliever** [comment]
We definitely support scalable UIs. This is done through the use of vector icons and the `units.dp()` macro, which allows you to define measurements in your application in terms of Google's DPI spec.

You can use this method like:

    Rectangle { x: units.dp(20) }

**Comment by ricardomv** [comment]
We follow the material design spec check http://www.google.com/design/spec/layout/metrics-keylines.html# and http://www.google.com/design/spec/layout/structure.html#
