### ISSUE TITLE
hide toolbar in view

### ISSUE THREAD

**Issue by marco-piccolino** [papyros/qml-material#135]

**Comment by marco-piccolino** [comment]
is there a recommended way to hide the appbar in a specific view?

**Comment by marco-piccolino** [comment]
is there a recommended way to hide the appbar in a specific view?

**Comment by jneidlinger** [comment]
Every page has a reference to it's ActionBar, which has a hidden property. Set it appropriately.

Page {
   actionBar.hidden: true
   ...
   ...
}

**Comment by marco-piccolino** [comment]
many thanks
