### ISSUE TITLE
PageStack demo broken: missing OverlayView.qml

### ISSUE THREAD

**Issue by marco-piccolino** [papyros/qml-material#136]
it seems OverlayView is missing from the current develop branch:

$ qmlscene demo/main.qml 
file:///Users/marco_piccolino/dev/workspace/maply-qt/modules/qml-material/demo/PageStackDemo.qml:45:2: Type OverlayView unavailable
file:///Applications/Qt/5.4/clang_64/qml/Material/OverlayView.qml: File not found

**Comment by jneidlinger** [comment]
Its definitely in develop:

https://github.com/papyros/qml-material/tree/develop/modules/Material

**Comment by ricardomv** [comment]
@marco-piccolino try running it with `qmlscene demo/main.qml -I modules`

**Comment by marco-piccolino** [comment]
@jneidlinger sorry, the issue reporting was quite sloppy - it's definitely not a missing file problem
@ricardomv thanks, the -I param does the trick

**Comment by marco-piccolino** [comment]
@ricardomv any idea about why it's not working without -I?

**Comment by jneidlinger** [comment]
@marco-piccolino you must tell QT what modules to use, -l tells it to "include" the subfolder, "modules" that contains a qmldir file which contains module information

**Comment by ricardomv** [comment]
Your installed version is not up to date with the git repo and you are trying to run the newer demo on the old library. The `-I` tells qmlscene to use the repo module instead of the installed.

**Comment by marco-piccolino** [comment]
thanks guys, it's clear now. I did reinstall but I guess I'd better remove the old version first.
