### ISSUE TITLE
Module "Material" is not installed

### ISSUE THREAD

**Issue by itatriev** [papyros/qml-material#137]
I've installed ```qml-extras``` and ```qml-material```. Application works properly when running on PC, but deploying it on Android gives me error described in the title. Any thoughts?

**Comment by jneidlinger** [comment]
Sounds like you are not packaging / loading the qml-extras and qml-material modules appropriately.

Can you show us what your main() looks like, before loading your root QML view?

**Comment by marco-piccolino** [comment]
@jneidlinger I had to manually copy the Material folder to Qt/5.4/android_armv7/qml to make it work. Is there a more appropriate way to install the module to non-host platforms?

**Comment by itatriev** [comment]
@jneidlinger Sure,
```c++
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);

    QQmlApplicationEngine engine;
    Wrapper jw;

    engine.rootContext()->setContextProperty("caller", &jw);

    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));

    return app.exec();
}
```

**Comment by boghison** [comment]
@itatriev @marco-piccolino is right, you have to run the appropriate qmake for android

**Comment by jneidlinger** [comment]
@marco-piccolino Yes, you either need to include the qml-material and qml-extras modules as part of your distributed package, or bundle the modules as part of your resources and reference them through the QRC system.

**Comment by jneidlinger** [comment]
@itatriev You need to tell the engine to include the proper modules before loading the QML file:

	engine.addImportPath("qmlmaterial/modules/");
	engine.addImportPath("qmlextras/modules/");

So it would be like this:

```
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);

    QQmlApplicationEngine engine;
    Wrapper jw;

    engine.rootContext()->setContextProperty("caller", &jw);
    engine.addImportPath("qmlmaterial/modules/");
    engine.addImportPath("qmlextras/modules/");
    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));

    return app.exec();
}
```

Where qmlmaterial/modules and qmlextras/modules are relative paths to those folders to the applications exectuable.

Alternatively you could package those directories into QRC files and be able to reference them as QRC paths, avoiding having to package the QML files alongside your exectuable:

	engine.addImportPath("qrc:/qmlmaterial/modules/");
	engine.addImportPath("qrc:/qmlextras/modules/");

**Comment by boghison** [comment]
@jneidlinger That is not necessary, you can install modules for QtAndroid just as for any version of Qt, it'll also take care of the inclusion of the packages into the app

**Comment by itatriev** [comment]
@boghison @jneidlinger @marco-piccolino 's solution helped me. Also, in ```engine.addImportPath("qmlmaterial/modules/");``` should I replace ```qmlmaterial/modules``` with ```path/to/qmlmaterial/modules``` or just leave it as is in case I'd like to use your solution to this problem.

**Comment by itatriev** [comment]
Anyway, thanks to all. You helped me a lot ;) You can mark the issue as solved.
