### ISSUE TITLE
change active tab programmatically

### ISSUE THREAD

**Issue by marco-piccolino** [papyros/qml-material#138]
I need to set the active tab of a tabview programmatically.
What's the recommended way of doing it?

(OT: @iBeliever it would be really nice, as already suggested, to have a Gitter channel for the project!)

**Comment by ricardomv** [comment]
TabView inherits ListView properties as you can see here https://github.com/papyros/qml-material/blob/develop/modules/Material/TabView.qml

**Comment by marco-piccolino** [comment]
thanks @ricardomv. Based on this, I add the following at the end of the SubPage definition of the demo, but nothing happens. Any clue?

````
Component.onCompleted: tabView.positionViewAtIndex(2, ListView.SnapOneItem)
````

**Comment by jneidlinger** [comment]
There is an initialization issue. positionViewAtIndex expects the delegate items to have non-zero dimensions (in this case width). 

Change the model to be:
```
    VisualItemModel {
        id: tabs

        // Tab 1 "Overview"
        Rectangle {
            width: tabView.width == 0 ? 1 : tabView.width
            height: tabView.height
            color: "green"
        }

        // Tab 2 "Projects"
        Rectangle {
            width: tabView.width == 0 ? 1 : tabView.width
            height: tabView.height
            color: "orange"
        }

        // Tab 3 "Inbox"
        Rectangle {
            width: tabView.width == 0 ? 1 : tabView.width
            height: tabView.height
            color: "purple"
        }
    }
```

Like that, having 

```
    TabView {
        id: tabView
        anchors.fill: parent
        currentIndex: page.selectedTab
        model: tabs
        
        Component.onCompleted: tabView.positionViewAtIndex(count - 1, ListView.SnapPosition)
    }
```

will work as expected.

That being said, this is a general QML / QT question. Please try to keep filed issues in scope of our Material QML framework, and not for general QML questions. There are plenty of better avenues for that.

**Comment by marco-piccolino** [comment]
@ricardomv thanks a lot for the explanation and sorry for the noise.
Being quite new to Qt, knowing whether an issue is framework-specific or general is not immediate, although a little more investigation would help discerning. I would recommend to open a Gitter channel or something similar exactly for this reason, so that questions which are not bugs or feature requests can be filtered by whoever is at hand and knowledgeable. Anyways, I'll try and do my homework better before enquiring.
Thanks again!
