### ISSUE TITLE
Version 0.2 - Objectives

### ISSUE THREAD

**Issue by iBeliever** [papyros/qml-material#159]
**Version Objective**

Release a monthly update to the framework, with more components and bug fixes.

**Major Deliverables**

- [ ] #157 - Set up a proper site/page for documentation, with proper versioning (0.1, 0.2, develop, etc.)
- [ ] More Material Design components

**Requirements for Release**

This version is due on May 31. In addition to the main deliverables, the following requirements must be met to release the version:

- [ ] No major bugs

**Release Retrospective**

*After releasing this version, add notes about what went well and what we can do better in the next version.*

**Comment by martin-mh** [comment]
Hello :) Maybe make a material TextArea :) ?
