### ISSUE TITLE
Units.pixelDensity default causes some units.dp usages to be wrong

### ISSUE THREAD

**Issue by jneidlinger** [papyros/qml-material#168]
With property real pixelDensity: 4.46

![withpixeldensitydefault](https://cloud.githubusercontent.com/assets/1914540/7277267/2440d802-e8dd-11e4-8c51-c26ec2be67e8.gif)

Remove the default, which is the way it used to be:

![withnopixeldensitydefault](https://cloud.githubusercontent.com/assets/1914540/7277283/31058650-e8dd-11e4-9d07-665b4335c9d4.gif)

**Comment by lnxseed** [comment]
one of my phone:
andorid, 4.3 inch, 720p , density 320
but "diagonal" is 9, return "tablet"

**Comment by iBeliever** [comment]
@jneidlinger If you have time, can you re-test this today with the `release/v0.1` branch? I'm hoping its fixed, either by the Units rename or another change to the list item.

**Comment by jneidlinger** [comment]
Sure. Looks like the units.qml file itself still doesn't have its casing updated? (Probably git ignoring it by default?)

https://github.com/papyros/qml-material/blob/release/v0.1/modules/Material/units.qml

**Comment by jneidlinger** [comment]
@iBeliever The issue appears to be fixed in current develop. You can close this issue. Thanks!

**Comment by iBeliever** [comment]
Great, thanks for checking!
