### ISSUE TITLE
units.multiplier reset

### ISSUE THREAD

**Issue by julien-m** [papyros/qml-material#173]
in ApplicationWindow and Window qml, when the Device.type is set, the units.multiplier is reset to "1" for mobile.

If we force the multiplier (eg: after the onCompleted) we lost it every time the mobile change between portrait/landscape.

I guess the multiplier should be initialized once.

**Comment by jneidlinger** [comment]
It is intentional, the multiplier should be 1 on Mobile.

**Comment by julien-m** [comment]
yes you right.

i played with the multiplier because the size between my app and an app made by google mismatch.
and after more test it's seems due to "generalized densities" (ldpi, mdpi...)
If I also generalizes dpi I am the same size

**Comment by iBeliever** [comment]
@julien-m So was this just a misunderstanding on your part or is the `units.dp()` method not correctly working on your device/screen? If this isn't a bug, please close the issue. Thanks!
