### ISSUE TITLE
Support for custom icons

### ISSUE THREAD

**Issue by marco-piccolino** [papyros/qml-material#175]
Although both Material and FontAwesome offer plenty of icons, there are many cases in which you want to use a custom svg for an Action.

Perhaps the Icon.name interface could support something like "custom/{qrc/path/to/icon.svg}"

**Comment by iBeliever** [comment]
Great idea! I'd like to implement this as follows in the Icon component:

    name: "action/settings"
    source: "icon://" + name

And then you could override the source property to something like:

    source: Qt.resolvedUrl("images/my_awesome_custom_icon.svg")

This would of course require iconName/iconSource pairs throughout the toolkit, but I think it's the cleanest solution to the problem. The other option is to drop the name property and just use `source: "icon://action/settings", but that might be a little more confusing.

**Comment by marco-piccolino** [comment]
thank for the quick inclusion! - the API looks good to me
