### ISSUE TITLE
Expose "input" of TextField in InputDialog

### ISSUE THREAD

**Issue by glaucopgomes** [papyros/qml-material#178]
I need to set the "inputMethodHints" of TextInput in the InputDialog. The "inputMethodHints" is very important to show the correct virtual keyboard in mobile devices, and expose the "input" will bring more utility and flexibility to InputDialog.

I can make these changes and make a "pull request".

What do you think?

**Comment by ricardomv** [comment]
Should be fixed in #154

**Comment by glaucopgomes** [comment]
OK, I saw your code and the solution I proposed no longer makes sense, but to solve my problem, it is still necessary to expose the "inputMethodHints" or TextField in InputDialog.

Should I close this issue and create a new one with the new solution or continue with that?

**Comment by iBeliever** [comment]
@glaucopgomes The TextField has now been ported to QtQuick.Controls - can you revisit this issue and update it as necessary so we can make any changes to fix your problem? Thanks!

**Comment by glaucopgomes** [comment]
@iBeliever, what I need actually is set the ```validator```, ```placeholderText```, ```text```, ```inputMethodHints``` and ```horizontalAlignment``` of the TextField of the InputDialog.

The InputDialog already exposes the first 3 + ```inputMask``` then, to my current need, expose  ```inputMethodHints``` and ```horizontalAlignment``` solve my issue, but I think the best thing to be done is expose the input, because someone else may need more than I

**Comment by iBeliever** [comment]
@glaucopgomes With the port to QtQuick.Controls, there isn't a way to expose the input object because that's an internal implementation detail of QtQuick.Controls. However, all the fields you need (and more) are already exposed by QtQuick.Controls: http://doc.qt.io/qt-5/qml-qtquick-controls-textfield.html.

**Comment by glaucopgomes** [comment]
I think you got me wrong, what I'm talking about is to simply put ```property alias input: textField``` into the InputDialog.

**Comment by iBeliever** [comment]
Apologies, I did misunderstand you. The comments about the port to QtQuick.Controls threw me off. I've exposed the input method hint directly as well as the text field itself in 9b8af87. I don't want to directly expose the horizontal alignment as Material Design only shows left-aligned text in text fields.

**Comment by glaucopgomes** [comment]
OK, this is what I need and you close the issue.
Sorry for the issue which I closed :blush:
