### ISSUE TITLE
Support preventing a popup from being dismissed

### ISSUE THREAD

**Issue by glaucopgomes** [papyros/qml-material#180]
This property is necessary for the dialog does not close when the user click or touch the overlay area.

Sometimes it is necessary to "lock" the screen while the user waits a long process, and this is not possible with the current implementation of PopupBase and OverlayLayer.

If you accept this enhancement, I can do it.

**Comment by iBeliever** [comment]
Great idea! If you want to implement it, let's name it `dismissOnTap` or something similar.

**Comment by glaucopgomes** [comment]
OK, I will do that.

**Comment by iBeliever** [comment]
Forgot to reference this from the commit, but @glaucopgomes implemented this in 12b9abdcf9b1605ca69b13e0055d4a4bfedff8e6.
