### ISSUE TITLE
ProgressBar/Circle requires Qt 5.4?

### ISSUE THREAD

**Issue by andreas-fatal** [papyros/qml-material#181]
When attempting to run the demo application on Qt 5.3 an error is reported when clicking on the Progress Bar tab in the application.
It seems ProgressBar.qml and ProgressCircle.qml requires Controls 1.3 and Control.Styles 1.3 (>= Qt 5.4?). Hacking these to simply use 1.2 instead seems to work (or atleast the demo application doesn't error). Should these be lowered (or should the documented required Qt version be bumped to 5.4)?

https://github.com/papyros/qml-material/blob/master/modules/Material/ProgressBar.qml#L20-L21
https://github.com/papyros/qml-material/blob/master/modules/Material/ProgressCircle.qml#L19-L20

**Comment by iBeliever** [comment]
I've updated the requirements in the README to require Qt 5.4, as we are using imports from that in several places. I believe at least one component (a QtQuick style) requires 5.4, and some others may as well. I don't have an installation of Qt 5.3, so I have no way of testing for backwards compatibility.
