### ISSUE TITLE
Bug in Android back button handling

### ISSUE THREAD

**Issue by glaucopgomes** [papyros/qml-material#189]
When you open and close a dialog, the back button does not "pops" the actual page.

**Comment by glaucopgomes** [comment]
This will be solved in the Pull Request #190

**Comment by iBeliever** [comment]
@glaucopgomes For future reference, please don't close bugs manually if a pull request will resolve it. I'll closes relevant bugs from the commit in the pull request. Thanks for reporting this bug, though!
