### ISSUE TITLE
How to visualize / test / develop

### ISSUE THREAD

**Issue by Sheraff** [papyros/qml-material#19]
I'd love to help out with this project. I'm definitely following it, I committed a change for efficiency, and I'm working on my side on a launcher (you said you wanted to package apps with the OS and I believe in great launchers). I'm a good enough (read "average") developer.

How do I use any of what's in this repo? I'm on OSX, within QT, things look weird and I'm not even sure I understand what I see.

Reference to docs would be enough, a quick tutorial would be great ;-)

**Comment by ricardomv** [comment]
we now have a working demo with examples for the library and documentation can be generated with qdoc. Please check http://doc.qt.io/qt-5/qml-tutorial.html for a tutorial on how to create a qml application
