### ISSUE TITLE
FontAwesome icons don't get colored correctly

### ISSUE THREAD

**Issue by andresmanz** [papyros/qml-material#197]
This is how the icons currently look in the demo, without setting a color:

![screenshot from 2015-05-03 01-28-57](https://cloud.githubusercontent.com/assets/7842959/7443104/dadec78c-f133-11e4-88e6-5327b8ae1137.png)

And this is how they look with the color set to ```Palette.colors["blue"]["500"]```:

![screenshot from 2015-05-03 01-31-57](https://cloud.githubusercontent.com/assets/7842959/7443109/65dc31e4-f134-11e4-943e-e9ceb9334544.png)

It's like that since yesterday, I think. AFAIK I didn't do anything special, so I hope you can reproduce this issue, too.

**Comment by ricardomv** [comment]
Reverting the changes in the [Icon.qml](https://github.com/papyros/qml-material/blob/develop/modules/Material/Icon.qml#L98) file, line 98 to `!=` fixes it, i don't know why tho.

**Comment by iBeliever** [comment]
@ricardomv I believe the reason that needs to be only one `=` instead of two is because `source` is a `url`, and we need casting when comparing it to a string.
