### ISSUE TITLE
TextField is incompatible with Layouts

### ISSUE THREAD

**Issue by itatriev** [papyros/qml-material#198]
`TextField` works properly alone, but when I want to use some kind of layout with it, it turns to be inaccessible.

**For instance, we have the following snippet of code:**
```qml
GridLayout {
    TextField {
        placeholderText: "Type in contact's name"
    }
    TextField {
        placeholderText: "Type in contact's phone"
     }
}
```
**The output will be:**

![](http://i.imgur.com/73yKQig.jpg)

**The possible expectation was something like:**

![](http://i.imgur.com/F22P9v8.jpg)

I mean, it doesn't react on clicking on it or typing smth into it.

**Comment by iBeliever** [comment]
This should be fixed now that we are using a QtQuick.Controls-based text field. Please reopen if you continue to have issues. Thanks!

**Comment by itatriev** [comment]
@iBeliever, thanks, I didn't notice it.
