### ISSUE TITLE
fontAwesome icons not displaying in actionBar's overflow menu [bug]

### ISSUE THREAD

**Issue by marco-piccolino** [papyros/qml-material#202]
![screen shot 2015-05-06 at 15 30 23](https://cloud.githubusercontent.com/assets/8167857/7493961/26a0c73c-f405-11e4-8348-5a84635fe692.png)

**Comment by marco-piccolino** [comment]
as a workaround (assuming that custom icons do get displayed in the overflow menu which I haven't cheked yet) if any icons people need are missing from the official material set, they can have a look at:

http://materialdesignicons.com/

**Comment by andresmanz** [comment]
Minimal case to reproduce:
```
ListItem.Standard {
    objectName: "action/test"
    text: "test"
    //iconName: "awesome/flask"
    iconSource: "icon://awesome/flask"
}
```

Uncomment iconName and it works.
