### ISSUE TITLE
I did not complie the test file. There is a fil and I do not understand it.  [bug]

### ISSUE THREAD

**Issue by H91011** [papyros/qml-material#216]
I have big problems about our project.

We are interesting in your Framework for Qt. But not working. Downloaded from github repository. After open qt and Open Projcet. Select Your Framework. Done
I click the run and debug project. And give error example: QtTest module not installed and Material not found.
After install QtTest on ubuntu software center. And re-debug and re-run give again error but different error.
"Application bar is unavaliable" but opened application in windows and close. Open and close. And blank windows only one shadow in left.

We recommend take video about for How to use Qml Material Design Framework How to debug. How to get solved form problems. We wish make fast about take video.

There is the screenshot: 
![photo_2015-05-27_18-04-18](https://cloud.githubusercontent.com/assets/8464532/7843840/2aa516ec-04b5-11e5-87b1-add736b87817.jpg)

**Comment by iBeliever** [comment]
Did you make sure you installed the qml-extras module as described in the README? (Also, on a side note, I'm going to be merging qml-extras into qml-material soon, so there won't be that added dependency.)

**Comment by H91011** [comment]
I am trying to qmake and make etc. in README. qmake is ok, but trying to make command give error :

![screen1](https://cloud.githubusercontent.com/assets/8464532/7844296/10b42bd0-04b8-11e5-97f1-0c61c83a5466.png)

so I only click qml-metarial.pro and open project and than I see the first fail.

**Comment by iBeliever** [comment]
You need to install the `qml-module-qttest` Ubuntu package.

**Comment by H91011** [comment]
I installed but again same error.

**Comment by eyelash** [comment]
Do you have the package `qtdeclarative5-dev` installed?

**Comment by iBelieve** [comment]
Closing to due lack of response from OP. Please reopen if this is still an issue.
