### ISSUE TITLE
I cannot compile on Arch

### ISSUE THREAD

**Issue by Pablotis** [papyros/qml-material#224]
Makefile:514: fallo en las instrucciones para el objetivo 'tests.o'
make[1]: *** [tests.o] Error 127
make[1]: se sale del directorio '/home/pablo/qml-material/tests'
Makefile:106: fallo en las instrucciones para el objetivo 'sub-tests-install_subtargets'
make: *** [sub-tests-install_subtargets] Error 2

**Comment by marco-piccolino** [comment]
hi, isn't this the same as #216?
