### ISSUE TITLE
Optimisations

### ISSUE THREAD

**Issue by martin-mh** [papyros/qml-material#227]
Hello everyone :)
I'm building a full app with your framework qml-material as front-end :)
It's really beautiful, thank you for that ! but there is only one issue.
The app use more than 100 mb of RAM (due to the front-end). I heard that Qt 5.5 will improve a lot the QML engine but do you have some tricks to optimise that :) ?
Thanks !

**Comment by marco-piccolino** [comment]
Hi Martin, you'd probably better upload some code so that people can figure out
