### ISSUE TITLE
Navigation Drawer new design

### ISSUE THREAD

**Issue by FiloSpaTeam** [papyros/qml-material#228]
Hi!
I think the navigation drawer need a new ui, new design it's like this:
![Navigation Drawer](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7bVdPRzZzeUE2bGc/patterns_navdrawer_metrics2.png)

What about? Thanks! :dancer:

**Comment by iBeliever** [comment]
We do need to implement a user switcher component. I've created #271 to track progress on this. Please re-open this issue if you think there is more we can do in addition to the user switcher component of the navdrawer.
