### ISSUE TITLE
Omit dynamic scoping issues

### ISSUE THREAD

**Issue by maufl** [papyros/qml-material#23]
Disclaimer, I do not know Qml very well.

For the last hours I tried to make a "working" App from the material components and by "working" I mean: it opens and looks good but does not do anything. So far I have not been successful.

From what I can see, a big issue is that a lot of components reference ids and properties which are not defined in the component document. For example the ActionBar component property maxActionCount refers to the toolbar id/property which is not defined in the ActionBar. This means it must be defined in the parent Qml object when instantiated, as far as I understand. Same for the currentPage property of the Page component. 

These references make it really hard to understand the components and use them correctly. After reading the [Qml docs](http://qt-project.org/doc/qt-5/qtqml-documents-scope.html#component-instance-hierarchy) it seems to me that this is also not recommended to do if it can be avoided, especially if you build reusable components.

I hope somebody with more Qml knowledge can confirm or refute this.

**Comment by iBeliever** [comment]
We've come a long way since this was opened. We've migrated to using QtQuick.Controls, which has been a huge benefit for cleaning up the code. Most of the scoping issues have been addressed. If there are any further concerns, please open issues for specific things.
