### ISSUE TITLE
Html tags in ApplicationWindow title cause incorrect text placement

### ISSUE THREAD

**Issue by malwoden** [papyros/qml-material#231]
```qml
import QtQuick 2.4
import Material 0.1

ApplicationWindow {
    visible: true
    initialPage: Page {
        id: page
        title: "<h1>Cool Title</h1>"
        tabs: []
    }
}
```

Will produce the following window:
![qml_tags](https://cloud.githubusercontent.com/assets/153354/8234736/b7a2fba0-15d5-11e5-846a-bbebb94b09d1.png)

And if the ```<h1>``` tags are removed you get the following:
![qml_notags](https://cloud.githubusercontent.com/assets/153354/8234747/c51cdbac-15d5-11e5-85bb-993111d760c4.png)

**Comment by malwoden** [comment]
Obviously this is down to http://doc.qt.io/qt-5/qml-qtquick-text.html#textFormat-prop

Would it be a sensible default in Label to set textFormat to Text.PlainText? I can't see much use for Style text in Label as a default, as it will conflict with Material's typography definitions.

**Comment by iBeliever** [comment]
I've set the textFormat of the title label in ActionBar to be plain text only. Material Design specifies the style and text size of the action bar title. If you have a good enough reason to change that, use `actionBar.customContent`,  as we do in the [Files app](https://github.com/papyros/files-app/blob/master/src/app/qml/FolderPage.qml#L70)
