### ISSUE TITLE
TextField behavior on Android.

### ISSUE THREAD

**Issue by cccco** [papyros/qml-material#233]
Hi, Papyros!

I found a strange behavior of the TextField at Android.

Signal onTextChanged does not working when I enter the letters, but the signal onTextChanged works well when I enter the other characters (such as numbers, and other characters are not letters).

That's too bad, because there is a processing text on this signal!

Sorry for my poor english.

Dmitri.

**Comment by cccco** [comment]
Hi, Papyros!

I found a solution for this problem.

Instead of the signal onTextChanged, you can use the signal onDisplayTextChanged. (Of course, for a password, this method is not suitable.)

The problem is not in the signal onTextChanged, but in the property "text". Instead of  property "text" you need to use  property "displayText" for text  processing.

Dmitri.

**Comment by koloboid** [comment]
Dmitri, this is QML's TextInput behavior, and not related to this project

**Comment by cccco** [comment]
Yes, i understood this. So, I close the issue.
