### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by espsousa** [papyros/qml-material#237]
Hi, I'm really new at QML, but I'm developing an application using qml-material from the papyros team. I'm really enjoying it and the application it's getting amazing thanks to all of you. Maybe in the future, if I learn it correctly, I could be a collaborator too. My question for now is: when will this component be added to the develop branch? The TimePicker was recently added, that's just amazing, but I really  need DatePicker as soon as possible too... :/ Could you, please, tell me something about this?

Thanks in advance

**Comment by ricardomv** [comment]
Merged in 39240f6
