### ISSUE TITLE
Error dialog, new component, child of Dialog

### ISSUE THREAD

**Issue by FiloSpaTeam** [papyros/qml-material#238]
We can make an ErrorDialog, child of Dialog that act like this:
```
Dialog {
            id: errorDialog
            dismissOnTap: true

            property var fnAccept: function() {}
            property var fnReject: function() {}

            onAccepted: fnAccept()
            onRejected: fnReject()
        }
```

We can in all the application have one Dialog that acts like an error dialog for everything.
Example:
![dialogerror](https://cloud.githubusercontent.com/assets/2974561/8328470/3c6da976-1a71-11e5-86cd-4b84799955db.png)

fnAccept and fnReject are pointers to lambda function and we can customize:
```
errorDialog.fnAccept = function() {
                    // custom accept for error dialog
                    btnLogin.clicked();
                }

errorDialog.fnReject = function() {
                    // custom reject for error dialog
                }
```

**Comment by iBeliever** [comment]
This is implemented by https://github.com/papyros/qml-material/commit/9f90c8e0591b3403090b7c573cca3b1997ad78b7.
