### ISSUE TITLE
Action keybindings don't work.

### ISSUE THREAD

**Issue by seanegoodwin** [papyros/qml-material#241]
I have been unable to get any sort of key binding to work with actions. I suspect it has something to do with focusing, but this is just a hunch.

An example:
```
import Material 0.1

ApplicationWindow {
    visible: true
    initialPage: Page {
        actions: [
            Action {
                iconName: "action/settings"
                keybinding: "Ctrl+F"
                onTriggered: console.log("Action triggered")
            }
        ]

    }
}
```

**Comment by Polyg0n** [comment]
If I had to assume, you would have to use a UTF-8 or hex code of key combo "Ctrl+F".
Like in JavaScript you would have to do:
```javascript
var unicode=e.keyCode? e.keyCode : e.charCode
alert(unicode)
}
```
So what I would try doing is, get the "char code/key code" of both "Ctrl" and "F", store that in a variable then when you use:

```qml
keybinding: 
```
It knows what you're talking about in terms of the "char code" and not a "String literal".

Just an idea, it might work!

Check your char code/key codes here:
http://jsbin.com/ojoku3/295/edit?html,output

**Comment by seanegoodwin** [comment]
According to qml-material's docs the keybinding just needs to be a string.
http://papyros.io/qml-material/qml-material-action.html

**Comment by Polyg0n** [comment]
I think see your issue now!

```qml
import Material 0.1

ApplicationWindow {
    visible: true
    initialPage: Page {
        actions: [
            Action {
                iconName: "action/settings"
                keybinding: "Ctrl-F" <---- "Ctrl+F" not "Ctrl-F"
                onTriggered: console.log("Action triggered")
            }
        ]
    }
}
```
There you are! Try that.

**Comment by seanegoodwin** [comment]
That's a mistake in my example code, but it doesn't work either way.

**Comment by seanegoodwin** [comment]
https://github.com/papyros/qml-material/pull/264 Fixes this.
