### ISSUE TITLE
Be able to assign an action to an ActionButton

### ISSUE THREAD

**Issue by oKcerG** [papyros/qml-material#249]
It would be useful to be able to assign an `Action` to an `ActionButton`, for example when the Action is also in the top ActionBar, or when the `Action` is provided externally.
Currently this can worked around like so:

    ActionButton {
        iconName: fooAction.iconName
        visible: fooAction.visible
        enabled: fooAction.enabled
        onClicked: fooAction.triggered(this)
    }

Ideally, we would only need to specify the action property (redefined from QuickControls `Button`) like so :

    ActionButton {
        action: fooAction
    }

**Comment by geiseri** [comment]
This would happen for free if the Material Action was based off of the QtQuick Action.  The problem is that the value "name" and "text" conflict.  They would have to be resolved, but that would break existing code.  If this is not an issue the change to QtQuick Action is pretty simple.

**Comment by oKcerG** [comment]
This is not sufficient, the `ActionButton` doesn't take into account the `iconName` and `visible` properties the `Action`
