### ISSUE TITLE
Android toast[suggestion]

### ISSUE THREAD

**Issue by ilnuribat** [papyros/qml-material#252]
I know, that you don't work with android, but have you got in a plan to create native android toast component?
http://developer.android.com/guide/topics/ui/notifiers/toasts.html

**Comment by dridk** [comment]
What about creating a multiOS feature ? 
    
    void showToast(msg) {
    #ifndef ANDROID_OS
    nativeToast(msg);
    #else ... 
    }

**Comment by glenfordwilliams** [comment]
currently we only support snackbars see the following demo code for an example
https://github.com/papyros/qml-material/blob/3c640c3ada124c73b4ae2aa555d6dfdc35d60584/demo/ButtonDemo.qml

All components are being written in qml so if you see the need to go native youll have make use of the QTs androidextras module

**Comment by iBeliever** [comment]
@ilnuribat Can you explain your usecase for using an Android Toast, and why you would like to use Android's native implementation of the Toast component versus our own implementation of a Toast?

We already provide a Snackbar component, which according to the [Google design guidelines](http://www.google.com/design/spec/components/snackbars-toasts.html#) provides a similar component. According to the guidelines:

> Android also provides a toast, primarily used for system messaging. Toasts are similar to snackbars but do not contain actions and cannot be swiped off screen.

It's very clear, but it seems toasts should be only used by the Android system and apps should use Snackbars instead.

**Comment by ilnuribat** [comment]
@iBeliever I have already read your answer, sorry for waiting so long time
Yes, snackbar is suffecient component for my application and it's requirements
https://github.com/papyros/qml-material/blob/develop/modules/Material/Snackbar.qml
I'm closing issue
