### ISSUE TITLE
Update the Material.Extras code to pass lint checks

### ISSUE THREAD

**Issue by iBeliever** [papyros/qml-material#260]
This is currently causing the Travis CI build to fail.

**Comment by 29jm** [comment]
I'm interested in fixing this bug, could you assign it to me?

**Comment by ricardomv** [comment]
@29jm you can just send a PR when you have one, we don't need to assign you to this issue.

**Comment by 29jm** [comment]
@ricardomv ok, just asked in case iBeliever had began to work on it, as this issue is assigned to him
