### ISSUE TITLE
[Beginner] Guide for Getting Started?

### ISSUE THREAD

**Issue by NLKNguyen** [papyros/qml-material#270]
Hi,

First of all, I'm impressed with the video demo of this project. I'm new to Qt/QML and have trouble figuring out how to make a simple Hello World app using this design. I need some help.

I followed the instruction to make install, and it's installed into my `/usr/lib/x86_64-linux-gnu/qt5`. Then in my main.qml, I put `import Material 0.1`, and the compiler said `module "Material" is not installed`

I use Qt Creator 3.4.2 (opensource) based on Qt 5.5.0

Thanks

**Comment by keugant** [comment]
Hi,
definitely agree with NLKNguyen, this is an awesome project and the demo is extremely impressive! But, also being a newbie with Qt/QML it is a bit daunting to figure out how to get started.

I'd be happy to contribute with fleshing out some documentation from some sample source code if that could help.

Thanks!

**Comment by ricardomv** [comment]
currently you don't need to install anything to start the demo you just need to clone the repo and run `qmlscene demo/main.qml -I modules`

**Comment by NLKNguyen** [comment]
Thanks for helping,

I have this error saying that QtQuick.Controls is not installed even though I can run a QtQuick.Controls application in QtCreator
```BASH
$ qmlscene demo/main.qml -I modules
file:///home/nnguyen/code/qml-material/demo/main.qml:5 Type ApplicationWindow unavailable
file:///home/nnguyen/code/qml-material/modules/Material/ApplicationWindow.qml:19 module "QtQuick.Controls" version 1.3 is not installed

```

**Comment by marco-piccolino** [comment]
Are you sure your qmlscene points to the 5.5 distribution? Perhaps there is
an older system version installed
Il 22/ago/2015 06:14 AM, "Nguyen Nguyen" <notifications@github.com> ha
scritto:

**Comment by marco-piccolino** [comment]
In which case just use the absolute path to the correct qmlscene
Il 22/ago/2015 09:24 AM, "Marco Piccolino" <marco.a.piccolino@gmail.com> ha
scritto:

**Comment by NLKNguyen** [comment]
Thanks, it works now :)
