### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by axed** [papyros/qml-material#273]
Hi there, i just wanted to ask if there's already some info material on how to use this nice qml lib?

My only experience so far is: download; open in QtCreator (Kit: Qt5.5 MSVC2013 64Bit); click execute; 6 Fails when building; no idea on how to go on.

Is the way to go to copy the qml files into your project and setup import paths for the QQmlApplicationEngine?

**Comment by mottosso** [comment]
Hello, have you tried following the installation instructions?

- https://github.com/papyros/qml-material#installation

**Comment by axed** [comment]
Actually not as MSVC is usally a Windows only compiler ;)
Usually there is an enviroment variable in linux session for QQmlApplicationEngine to find extra Qml modules as qml-material on a specified path such as /usr/share/whatever/shiny-qml-modules.
So if i understood that right, the way to go is to import the whole project ('s path) with QQmlEngine's addImportPath method?

**Comment by mottosso** [comment]
This works for me.

```bash
$ qmake
$ nmake
$ nmake install
```

It'll copy Material to the default QML library directory, which may or may not be what you want. Alternatively, you can do as you say, clone the repository and either add it using addImportPath or via the QML2_IMPORT_PATH environment variable.

- [Reference](http://doc.qt.io/qt-5/qtqml-syntax-imports.html)

**Comment by marco-piccolino** [comment]
@axed did you manage to get it working?

**Comment by axed** [comment]
@marco-piccolino sadly not.
I copied the cloned "qml-material" folder to "C:/Qt/qml/" and created a new QmlApplication from scratch.
This is the main.cpp:
```
#include <QApplication>
#include <QQmlApplicationEngine>
int main(int argc, char *argv[]) {
    QApplication app(argc, argv);
    QQmlApplicationEngine engine;
    engine.addImportPath("C:/Qt/qml/qml-material/modules/QtQuick/Controls/Styles/Material");
    engine.addImportPath("C:/Qt/qml/qml-material/modules/Material");
    engine.addImportPath("C:/Qt/qml/qml-material/modules/Material/Extras");
    engine.addImportPath("C:/Qt/qml/qml-material/modules/Material/Extras/images");
    engine.addImportPath("C:/Qt/qml/qml-material/modules/Material/Extras/js");
    engine.addImportPath("C:/Qt/qml/qml-material/modules/Material/fonts/fontawesome");
    engine.addImportPath("C:/Qt/qml/qml-material/modules/Material/fonts/roboto");
    engine.addImportPath("C:/Qt/qml/qml-material/modules/Material/ListItems");
    engine.load("C:/Qt/qml/qml-material/demo/main.qml");
    return app.exec();
}
```

Aaaaand this was the result:
```
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
file:///C:/Qt/qml/qml-material/demo/main.qml:3 module "Material.ListItems" is not installed
file:///C:/Qt/qml/qml-material/demo/main.qml:2 module "Material" is not installed
file:///C:/Qt/qml/qml-material/demo/main.qml:3 module "Material.ListItems" is not installed
file:///C:/Qt/qml/qml-material/demo/main.qml:2 module "Material" is not installed
```
I skipped to add all the import paths for the icons, but yet i'm not really sure why it fails to load the "Material.ListItems" module :/

**Comment by marco-piccolino** [comment]
what do you get if you just set engine.addImportPath("C:/Qt/
qml/qml-material/modules"); ?

**Comment by axed** [comment]
```
#include <QApplication>
#include <QQmlApplicationEngine>
int main(int argc, char *argv[]) {
    QApplication app(argc, argv);
    QQmlApplicationEngine engine;
    engine.addImportPath("C:/Qt/qml/qml-material/modules");
    engine.load("C:/Qt/qml/qml-material/demo/main.qml");
    return app.exec();
}
```
Literally nothing happens. No errors are printed, no window opens up.
Just the good'ol
```
QML debugging is enabled. Only use this in a safe environment.
```
Message.

**Comment by marco-piccolino** [comment]
@axed you might want to head to the Gitter chat to get additional support,
it might be easier.
Sadly I have no experience with Qt on Windows.

**Comment by mottosso** [comment]
It looks like you're loading the QML file, but not actually showing the resulting window.

You can either listen for the completion event on the Engine, or use [QQuickView](http://doc.qt.io/qt-5/qquickview.html#source-prop) instead to set the source. With that, it'll pop up once it has loaded.

**Comment by axed** [comment]
@mottosso you pointed me in the totally right direction! The demo/main.qml file misses the "visible: true" property in the ApplicationWindow Object, that's why nothin' showed up... i feel kinda cheap now.
So thank you everyone, now i can move onto #230 ^^

**Comment by iBeliever** [comment]
@axed Just added `visible: true` to the demo for people launching it from C++. Sorry for the confusion!

**Comment by axed** [comment]
@iBeliever totally not a prob! Nice to see how vital this project is :)
