### ISSUE TITLE
android woes

### ISSUE THREAD

**Issue by glenfordwilliams** [papyros/qml-material#279]
so ive been testing out some code on the android side and the first thing that popped out to me was the fact that both the actionbar and Navigationdrawer were too small as well as missing icons

before this project started i was able to solve the scaling issues using the following code 
`
#include <QScreen>
#ifdef Q_OS_ANDROID
#include <QtAndroidExtras>
#endif

    QScreen *screen = qApp->primaryScreen();
    int dpi = screen->physicalDotsPerInch() * screen->devicePixelRatio();
    bool isMobile = false;

#if defined(Q_OS_IOS)
    // iOS integration of scaling (retina, non-retina, 4K) does itself.
    dpi = screen->physicalDotsPerInch();
    isMobile = true;
#elif defined(Q_OS_ANDROID)
    // https://bugreports.qt-project.org/browse/QTBUG-35701
    // recalculate dpi for Android

    QAndroidJniEnvironment env;
    QAndroidJniObject activity = QtAndroid::androidActivity();
    QAndroidJniObject resources = activity.callObjectMethod("getResources", "()Landroid/content/res/Resources;");
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();

        return EXIT_FAILURE;
    }

    QAndroidJniObject displayMetrics = resources.callObjectMethod("getDisplayMetrics", "()Landroid/util/DisplayMetrics;");
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();

        return EXIT_FAILURE;
    }
    dpi = displayMetrics.getField<int>("densityDpi");
    isMobile = true;
#else
    // standard dpi
    dpi = screen->logicalDotsPerInch() * screen->devicePixelRatio();
#endif

    // now calculate the dp ratio
    qreal dp = dpi / 160.f;

    QQmlApplicationEngine engine;
    QQmlContext *context = engine.rootContext();
    context->setContextProperty(QStringLiteral("utils"), new Utils(&engine));
    context->setContextProperty(QStringLiteral("initialUrl"),
                                Utils::fromUserInput(initialUrl));
    
    QRect geometry = QGuiApplication::primaryScreen()->availableGeometry();
    if (!QGuiApplication::styleHints()->showIsFullScreen()) {
        const QSize size = geometry.size() * 4 / 5;
        const QSize offset = (geometry.size() - size) / 2;
        const QPoint pos = geometry.topLeft() + QPoint(offset.width(), offset.height());
        geometry = QRect(pos, size);
    }

    context->setContextProperty("dp", dp);
        context->setContextProperty("isMobile", isMobile);
    context->setContextProperty(QStringLiteral("initialX"), geometry.x());
    context->setContextProperty(QStringLiteral("initialY"), geometry.y());
    context->setContextProperty(QStringLiteral("initialWidth"), geometry.width());
    context->setContextProperty(QStringLiteral("initialHeight"), geometry.height());
`

![screenshot_2015-09-15-17-28-02](https://cloud.githubusercontent.com/assets/1114368/9892834/3970f6e4-5bd8-11e5-80b5-8ebee1163566.png)
![screenshot_2015-09-15-17-28-13](https://cloud.githubusercontent.com/assets/1114368/9892833/39704366-5bd8-11e5-86dc-189775560b54.png)
![screenshot_2015-09-15-17-28-16](https://cloud.githubusercontent.com/assets/1114368/9892835/3974a08c-5bd8-11e5-9518-6488c0bc484a.png)
![screenshot_2015-09-15-18-01-35](https://cloud.githubusercontent.com/assets/1114368/9892836/39768fc8-5bd8-11e5-9a30-a67c77476fea.png)
![screenshot_2015-09-15-17-27-52](https://cloud.githubusercontent.com/assets/1114368/9892837/3978365c-5bd8-11e5-9f8c-b5a7f19fd7d3.png)

**Comment by iBeliever** [comment]
Interestingly enough, the text and tooltip seem to be the right size, so the issue doesn't seem related to DPI calcuations specifically.

**Comment by glenfordwilliams** [comment]
It's strange that the screenshots look OK, gonna take a shot on another
device

**Comment by glenfordwilliams** [comment]
This screen looked way smaller mine

**Comment by iBelieve** [comment]
The screen resolution calculations should be fixed on Qt 5.6 and hopefully on previous versions as well. Please open a new issue if you're facing problems after the latest code changes. Thanks!
