### ISSUE TITLE
Expose dp() in the (Application)Window

### ISSUE THREAD

**Issue by marco-piccolino** [papyros/qml-material#289]
Exposing dp() as a function in (Application)Window could save tons of Units.dp() typing

**Comment by marco-piccolino** [comment]
as to components, maybe it's worth exposing it in a basic type like View?

**Comment by koloboid** [comment]
+100
I'm doing the same for my apps

**Comment by iBeliever** [comment]
Would love to do this in a way that each window can scale independently (though I think that won't be necessary with Qt 5.6, which will do the scaling itself). The problem is exposing it in a way that works with the QtQuick.Controls style when used to style existing apps without the full framework.

**Comment by iBelieve** [comment]
This is now implemented via the recent refactoring. Just use `dp(?)` in any project that uses one of the Material top-level components. It's also different for each window on different screens, which is really nice.
