### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by leoxnidas** [papyros/qml-material#302]
W/libRobotHand.so( 5383): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Icon.qml:63 ((null)): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Icon.qml:63:5: QML Image: Invalid image data: file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/icons/navigation/close.svg
W/libRobotHand.so( 5383): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Icon.qml:63 ((null)): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Icon.qml:63:5: QML Image: Invalid image data: file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/icons/navigation/close.svg
W/libRobotHand.so( 5383): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Icon.qml:63 ((null)): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Icon.qml:63:5: QML Image: Invalid image data: file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/icons/navigation/close.svg
W/libRobotHand.so( 5383): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Icon.qml:63 ((null)): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Icon.qml:63:5: QML Image: Invalid image data: file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/icons/navigation/close.svg
W/libRobotHand.so( 5383): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Toolbar.qml:69 ((null)): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Toolbar.qml:69: TypeError: Cannot read property 'color' of undefined
W/libRobotHand.so( 5383): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Toolbar.qml:113 ((null)): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Toolbar.qml:113: TypeError: Cannot read property 'rightSidebar' of undefined
W/libRobotHand.so( 5383): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Toolbar.qml:152 ((null)): file:///data/data/org.humboldt.hand/qt-reserved-files/qml/Material/Toolbar.qml:152: TypeError: Cannot read property 'rightSidebar' of undefined

**Comment by marco-piccolino** [comment]
You need to add qt+=svg in your .pro file.

Also, you need a Page component as your ApplicationWindow's initialPage
property
Il 05/ott/2015 01:02 AM, "Leonardo Esparis" <notifications@github.com> ha
scritto:

**Comment by aleixpol** [comment]
Linking to QtSvg fixed the issue for me as well.

**Comment by moonshadow565** [comment]
Also if you develop to android you should add.
#include <QtSvg> do your main.cpp because deployment proccess sometimes "forgets" to pick svg up.

**Comment by leoxnidas** [comment]
ty.. it works..
