### ISSUE TITLE
Ink animation and several clicks

### ISSUE THREAD

**Issue by Mr1Penguin** [papyros/qml-material#308]
Hello!
Started to use qml-material in my project and noticed that I can't have two(three/4/etc) ink animations on the same element. The new animation doesn't start while current is active.
This is original idea or i can find and push solution?

**Comment by sk2212** [comment]
I think this is not specified in Googles Material Design Spec, isn`t it?

**Comment by malwoden** [comment]
I don't believe this is the specified behaviour, and playing around with some Material apps on Android (G+, Music) it appears that multiple concurrent ink animations are allowed.

**Comment by aleixpol** [comment]
+1 for a solution.
Also note the warning:
`file:///home/kde-devel/kde5/qml/Material/Ink.qml:61: TypeError: Cannot call method 'removeCircle' of null
`
