### ISSUE TITLE
page's  parameter

### ISSUE THREAD

**Issue by lnxseed** [papyros/qml-material#310]
Can I pass parameter between two page with pagestack?

**Comment by marco-piccolino** [comment]
Yes you can. pageStack inherits from StackView, so the usual syntax works:
pageStack.push({item: someItem, properties: {fgcolor: "red", bgcolor: "blue"}})
see http://doc.qt.io/qt-5/qml-qtquick-controls-stackview.html

For questions of this kind, you'd better use the gitter chat. Please don't forget to close this issue.

**Comment by lnxseed** [comment]
good, thanks @marco-piccolino
