### ISSUE TITLE
Windows : secondaryItem not visible in ListItem.Subtitled

### ISSUE THREAD

**Issue by neitsa** [papyros/qml-material#319]
**System**: Windows 10 x64
**Qt version**: Qt 5.5.1 (msvc2013 x64)
**Current commit tested**:
$ git show
commit 42da3ad60a8e4e086b106cd300c3b809b372cf2d

Note: tested only  with demo program (`qml-material\demo\main.qml`)
Command line: `qmlscene ./demo/main.qml`

The secondary item in ListItem.Subtitled is not visible in the demo program (there should be a Switch item visible):

![listitem1](https://cloud.githubusercontent.com/assets/4538670/10716073/52b4d0e4-7b2c-11e5-99ec-6ba7d2ae2717.PNG)

Item source:

```javascript
ListItem.Subtitled {
    text: "Subtitled list item"
    subText: "With some subtext, icon, and secondary item!"
    secondaryItem: Switch {
        id: enablingSwitch
        anchors.verticalCenter: parent.verticalCenter
    }

    onClicked: enablingSwitch.checked = !enablingSwitch.checked
```

Commenting the *visible* attribute line in [modules/Material/ListItems/Subtitled.qml] (https://github.com/papyros/qml-material/blob/develop/modules/Material/ListItems/Subtitled.qml#L153) will automatically make the secondaryItem to appear:

```javascript
Item {
    id: secondaryItem
    Layout.alignment: Qt.AlignCenter
    Layout.preferredWidth: childrenRect.width
    Layout.preferredHeight: parent.height
    Layout.column: 4

    //visible: visibleChildren.length > 0
```

![listitem2](https://cloud.githubusercontent.com/assets/4538670/10716094/595a9ee6-7b2d-11e5-8b49-f70267afb91b.PNG)

**Comment by jneidlinger** [comment]
This is fixed in my PR here https://github.com/papyros/qml-material/pull/298

**Comment by neitsa** [comment]
@jneidlinger Thanks a lot! My bad, I haven't seen your issue report because I searched for "secondaryItem"...

Anyway thanks a lot for your PR. I'll close this issue since this is clearly a duplicate.
