### ISSUE TITLE
Ink containsMouse stays always true after it's pressed on mobile

### ISSUE THREAD

**Issue by oKcerG** [papyros/qml-material#321]
When you press something that has an `Ink`, it will then always look as hovered even if you release the touch or press another element.
Example :
![image](https://cloud.githubusercontent.com/assets/349268/10821289/ee91ecc2-7e51-11e5-9d56-8f46964db41a.png)
Here 2, 4 and 6 have been pressed previously and 3 is being pressed.
Reproduced on Android & iOS

**Comment by nbigaouette** [comment]
I'm developing an application in QML using qml-material meant to be run on an linux desktop with a touchscreen. I see the same problem where touched elements keep their ink'ed state. Would be interested for a solution to this...

**Comment by iBeliever** [comment]
I wonder if this is an upstream issue we should report? Seems like MouseArea.containsMouse isn't getting set back to false after a touch.
