### ISSUE TITLE
Demo program doesn't retain currently selected tab

### ISSUE THREAD

**Issue by neitsa** [papyros/qml-material#332]
**System**: Windows 10 x64
**Qt version**: Qt 5.5.1 (msvc2013 x64)
**Current commit tested**:
$ git show
commit 3c9f4e1d88ccc977adf68c2299a3c86b221ef5e8

Main problem: Demo program doesn't keep the actually selected tab. If the window is minimized in width, the program UI become unusable.

Repro steps

* Start demo program and select the 2nd (basic components) or 3rd (compound components) tab:

![capture1](https://cloud.githubusercontent.com/assets/4538670/11015641/fa27a2d2-8565-11e5-90b0-b6e489ebba92.PNG)

* Minimize the width of the main window so the tab headers disappear (notice that we are back to the content of the first tab in the main view):
![capture2](https://cloud.githubusercontent.com/assets/4538670/11015642/14384960-8566-11e5-9d5f-093de530fc8b.PNG)

* Getting back to the original width (or at least a sufficient width for the tab headers to reappears), the 3rd tab is still selected but the content in the view is the one from the 1st tab. Clicking one any of the tab headers doesn't change the main view, so the program became unusable: 

![capture3](https://cloud.githubusercontent.com/assets/4538670/11015662/b8ec53ca-8566-11e5-94f8-c5bfa472c289.PNG)

**Comment by dafky2000** [comment]
+1 on this. I also experience this problem.

**System:** Arch Linux x64
**Qt version:** Qt 5.5.1 (GCC 5.3.0, 64 bit)
**Current commit tested:** Latest commit b714c9c
