### ISSUE TITLE
Page/tabs: TabBar.qml:171:27: Unable to assign [undefined] to QString

### ISSUE THREAD

**Issue by ukoehler** [papyros/qml-material#341]
Hi there,

I have created an application using Page/tabs and everything works fine with Windows/Qt5.4.1, however, with Linux/Qt5.5.1 the tab text doesn't show and I get
`...TabBar.qml:171:27: Unable to assign [undefined] to QString`

Any ideas? The following code is enough to reproduce the behaviour:

    import QtQuick 2.2
    import Material 0.1
    import Material.ListItems 0.1 as ListItem
    
    ApplicationWindow {
        id: appicationwindow
    
        visible: true
        width: 220
        height: 220
    
        title: "papyros/qml-material Application Window test"
    
        initialPage: mainpage
    
    
        Page {
            id: mainpage
            title: "Main Page Title"
    
            //anchors.fill: parent
    
            actionBar.maxActionCount: 1
    
            tabs: [
                // Each tab can have text and an icon
                {
                    text: "Tab1",
                    icon: "action/home"
                },
                {
                    text: "Tab2",
                    icon: "action/home"
                },
                {
                    text: "Tab3",
                    icon: "action/home"
                }
            ] // tabs
    
    
        } // Page
    
    }

This produces:

    qmlscene ApplicationWindowTestShort.qml 
    file:///usr/local/Qt-5.5.1/5.5/gcc_64/qml/Material/TabBar.qml:171:27: Unable to assign [undefined] to QString
    file:///usr/local/Qt-5.5.1/5.5/gcc_64/qml/Material/TabBar.qml:171:27: Unable to assign [undefined] to QString
    file:///usr/local/Qt-5.5.1/5.5/gcc_64/qml/Material/TabBar.qml:171:27: Unable to assign [undefined] to QString

Any help is greatly appreciated

Cheers

Uwe

**Comment by ukoehler** [comment]
Same problem on Windows with Qt 5.5.1 and todays papyros/qml-material snapshot. I can see the tabs when starting the main.qml demo. Seems like I haven't understood the usage of the tabs.

**Comment by neitsa** [comment]
You need to use `title` for the tab text and `iconName` (or `iconSource`) for the icon. 

```javascript
import QtQuick 2.4
import Material 0.1

ApplicationWindow {
    id: appicationwindow

    visible: true
    width: 220
    height: 220

    title: "papyros/qml-material Application Window test"

    initialPage: mainpage

    Page {
        id: mainpage
        title: "Main Page Title"

        anchors.fill: parent

        actionBar.maxActionCount: 1

        tabs: [
            // Each tab can have text and an icon
            {
                title: "Tab1",
                iconName: "action/home",
                enabled: true
            },
            
            {
                title: "Tab2",
                iconName: "action/home",
                enabled: true
            },
            
            {
                title: "Tab3",
                iconName: "action/home",
                enabled: true
            }
        ] // tabs
    } // Page
}
```


Adding `enabled` boolean property will avoid a problem in TabBar.qml which says something like:

    file:////qml/Material/TabBar.qml:141:26: Unable to assign [undefined] to bool

Which leads to this line in `TabBar.qml`:

                enabled: tab.enabled

I guess that `tab.enabled` is undefined if not explicitly defined.

**Comment by ukoehler** [comment]
Dear neltsa,

many thanks for your help. 

I found a similar solution by digging into the code. I believed I needed to use TabbedPage, but that is not necessary. I do not need `enabled: true`, by the way.

I didn't find any documentation that had to be changed. That would have helped.

Cheers

Uwe
