### ISSUE TITLE
WindowDecorations throws error

### ISSUE THREAD

**Issue by marco-piccolino** [papyros/qml-material#344]
@iBeliever the recent introduction of WindowDecorations throws the following. Perhaps an extra check is needed?

 ```
qrc:///qml-material/modules/Material/WindowDecorations.qml:50 ((null)): qrc:///qml-material/modules/Material/WindowDecorations.qml:50: Error: Qt.createQmlObject(): failed to create object:
qrc:///qml-material/modules/Material/PapyrosWindowDecorations:1:1: module "Papyros.Desktop" is not installed
```

**Comment by shaoxie1986** [comment]
I got the same error.

**Comment by Tim15** [comment]
Looks like an issue with qml-material. You should report it there.

**Comment by Tim15** [comment]
iBeliever recently refactored all that into a new PlatformExtension system. Try updating to see if that fixes it.

**Comment by marco-piccolino** [comment]
@Tim15 thank you for the pointer. @iBeliever there was a small typo in the qmldir, see #349

**Comment by iBeliever** [comment]
I'm going to close this as a duplicate of #351 even though this was created first because the other ticket is more relevant after the refactoring.
