### ISSUE TITLE
Error: module "Papyros.Material" is not installed

### ISSUE THREAD

**Issue by Philip-Trettner** [papyros/qml-material#351]
I'm trying to use QML Material in a non-papyros project (and I hope it's also intended to work that way).

I've compiled all module qml files into a qrc and when starting the demo page, I get the following errors on the console:
```
qrc:///modules/Material/PlatformExtensions.qml:43: Error: Qt.createQmlObject(): failed to create object: 
qrc:///modules/Material/PapyrosExtensions:1:1: module "Papyros.Material" is not installed
```

However, the page itself works.

When looking at the offending code, I've noticed `import Papyros.Material 0.1;` (modules/Material/PlatformExtensions.qml:43).

Could it be that this should be `import Material 0.1;` instead?

**Comment by iBeliever** [comment]
The code is correct and that missing module is to be expected if you're not running on Papyros. That module is a way we can add additional behavior on Papyros without putting the code directly in qml-material. The problem is getting that error message to not show.

**Comment by Philip-Trettner** [comment]
Hm, how about providing a dummy Papyros.Material module in this repository?
Not sure if a module can be empty, but maybe with a dummy qml that does nothing.

Would that work?

**Comment by Philip-Trettner** [comment]
I've added 
```
qmlRegisterType<QQuickItem>("Papyros.Material", 0, 1, "DummyItem");
```
to my C++ code and this seems to resolve the missing module problem.

However, now I get 
```
QQmlComponent: Component creation is recursing - aborting
```
probably from the same location, because PlatformExtensions is reinstantiating itself?
