### ISSUE TITLE
[Beginner] How to import material lib on Android project 

### ISSUE THREAD

**Issue by ducmaxime** [papyros/qml-material#352]
Hello, I am a beginner with QTCreator.

Can you explain me how import your lib on Quick Application project. 

<img width="479" alt="screen shot 2016-01-05 at 11 42 03" src="https://cloud.githubusercontent.com/assets/6499846/12113185/67bbb554-b3a1-11e5-8d97-c22abc2e52e9.png">

Thank you.

**Comment by tim-sueberkrueb** [comment]
@ducmaxime You need to include the `Material` module in your android Kit. The easiest way is just moving the folder: 
Assuming your Qt installation is in `.../Qt/`you need to move the `Material` folder to `.../Qt/5.5/android_armv7/qml/Material` or  `.../Qt/5.5/android_armv5/qml/Material` depending on your installation. Then you should be able to build it selecting the android kit.

**Comment by ducmaxime** [comment]
Thank you, it's work fine !

**Comment by ducmaxime** [comment]
I can't install library on IOS.
Any Idea ?

**Comment by joselitofilho** [comment]
Thank you, it's work for me in Android.

**Comment by christian-vrl** [comment]
tim-sueberkrueb  , your comment is a life saver !!!! Thanks !!!

**Comment by timsueberkrueb** [comment]
@joselitofilho @christian-vrl :)
The proper way to do this is doing something like the following at the root of your QML Material clone:
```sh
mkdir build && cd build
<path-to-qt>/android_armv7/qmake ..
make
make install
```
Or use the per-project installation method: https://github.com/papyros/qml-material#per-project-installation-using-git-submodules-and-qmake

**Comment by timsueberkrueb** [comment]
Note: This project is no longer maintained.
If you have Qt >= 5.7 and you're looking for Material style with QtQuick, checkout the new [QtQuick Controls 2](https://doc.qt.io/qt-5/qtquickcontrols2-index.html) and [Fluid](http://github.com/lirios/fluid).

**Comment by yasser-sobhy** [comment]
Also check out Gurra  https://github.com/yasser-sobhy/Gurra , a new qml ui
framework with ready-made components and a central app component.

Gurra was just released few days ago and the documentation is still being
written .
