### ISSUE TITLE
Clean up the module structure

### ISSUE THREAD

**Issue by iBeliever** [papyros/qml-material#363]
@marco-piccolino was suggesting in #328 that we should restructure the library into multiple submodules for core components, additional components, etc.

Here's one possible module structure that splits components into several well-defined modules (I'd have to go though each component and make sure they're in the right modules based on their dependencies, but this would be a rough draft):

    Material
    ├── Components                              // Material Design components not in QtQuick.Controls
    │   ├── ActionButton.qml
    │   ├── Card.qml
    │   ├── DatePicker.qml
    │   ├── IconButton.qml
    │   ├── MenuField.qml
    │   ├── ProgressCircle.qml
    │   ├── Scrollbar.qml
    │   ├── Sidebar.qml
    │   ├── Snackbar.qml
    │   ├── ThinDivider.qml
    │   ├── TimePicker.qml
    │   ├── Tooltip.qml
    │   └── Wave.qml
    ├── Controls                                // Materialized version of QtQuick.Controls
    │   ├── Action.qml
    │   ├── Button.qml
    │   ├── CheckBox.qml
    │   ├── Label.qml
    │   ├── ProgressBar.qml
    │   ├── RadioButton.qml
    │   ├── Slider.qml
    │   ├── Switch.qml
    │   ├── Tab.qml
    │   └── TextField.qml
    ├── Core                                    // Core Material stuff
    │   ├── AwesomeIcon.qml
    │   ├── Device.qml
    │   ├── Icon.qml
    │   ├── Ink.qml
    │   ├── MaterialAnimation.qml
    │   ├── Object.qml
    │   ├── Palette.qml
    │   ├── PlatformExtensions.qml
    │   ├── Theme.qml
    │   ├── ThemePalette.qml
    │   ├── Units.qml
    │   └── View.qml
    ├── Extras                                  // Extra stuff that nothing else depends on
    │   ├── AutomaticGrid.qml
    │   ├── CMakeLists.txt
    │   ├── CircleImage.qml
    │   ├── CircleMask.qml
    │   ├── ColumnFlow.qml
    │   ├── Image.qml
    │   ├── images
    │   │   └── circle.png
    │   ├── js
    │   │   ├── dateutils.js
    │   │   ├── httplib.js
    │   │   ├── listutils.js
    │   │   ├── promises.js
    │   │   └── utils.js
    │   └── qmldir
    ├── ListItems                               // List items
    │   ├── BaseListItem.qml
    │   ├── CMakeLists.txt
    │   ├── Divider.qml
    │   ├── SectionHeader.qml
    │   ├── SimpleMenu.qml
    │   ├── Standard.qml
    │   ├── Subheader.qml
    │   ├── Subtitled.qml
    │   └── qmldir
    ├── Popups                                  // Popups, dialogs, popovers, etc
    │   ├── BottomActionSheet.qml
    │   ├── BottomSheet.qml
    │   ├── Dialog.qml
    │   ├── Dropdown.qml
    │   ├── InputDialog.qml
    │   ├── OverlayView.qml
    │   ├── Popover.qml
    │   ├── PopupBase.qml
    │   └── TimePickerDialog.qml
    └── Window                                  // Stuff that requires a custom root component to work
        ├── ActionBar.qml
        ├── AppTheme.qml
        ├── ApplicationWindow.qml
        ├── MainView.qml
        ├── NavigationDrawer.qml
        ├── OverlayLayer.qml
        ├── Page.qml
        ├── PageSidebar.qml
        ├── PageStack.qml
        ├── TabBar.qml
        ├── TabbedPage.qml
        ├── Toolbar.qml
        └── Window.qml

@marco-piccolino @ricardomv @geiseri @jneidlinger @oKcerG what do you guys think of this module layout? Are there too many modules, or this a good amount with good criteria for separation?

**Comment by marco-piccolino** [comment]
@iBeliever the general structure of modules looks good to me. The division between Components and Controls is quite artificial, but given that QtQuick.Controls 1 is unlikely to change it could work and it's a good way to bootstrap existing non-material apps by just adding the import. However, do you have real use cases for using the material theme with existing apps?

I'd also suggest to include a FontLoader to the theme with a configurable source to make it easy to use custom fonts. I'd say Roboto Regular and Medium are reasonable default faces for inclusion. All components which display text (Label etc.) should then access the theme font to get the font name. Non-latin systems would need to use Noto anyways. Extra Roboto faces could make a separate module. Noto could make another module.

**Comment by marco-piccolino** [comment]
Given than Controls 2 has a material style there might be no need to provide compatibility with Controls.

**Comment by geiseri** [comment]
I checked it out.  It is material "style" but not in behavior.  Also its only in labs and will not be until 5.7 at best.  I think the advantage of controls compatibility will be with accessibility and creature features like keyboard accelerators.  The thing is if you want something that follows the material spec you will still want something like qml-material.
