### ISSUE TITLE
How to compile and install in Windows 7？

### ISSUE THREAD

**Issue by lixiang19870818** [papyros/qml-material#365]
How to compile and install in Windows 7？ mingw32-make complie error

**Comment by Cheapskate01** [comment]
The library uses QT, not GCC (AFAIK) so a gcc derivitive wouldn't work too well.

**Comment by SuicSoft** [comment]
Install Linux inside virtual box

**Comment by iBelieve** [comment]
This issue tracker is not a support forum. If you have a support-related question specific to qml-material, please join our Gitter channel listed on the README. Otherwise, please use a more general Qt support channel, such as IRC, mailing lists, or forums.
