### ISSUE TITLE
used error code

### ISSUE THREAD

**Issue by lixiang19870818** [papyros/qml-material#366]
file:///C:/Qt/Qt5.4.2/5.4/mingw491_32/qml/Material/PlatformExtensions.qml:43: Error: Qt.createQmlObject(): failed to create object: 
    file:///C:/Qt/Qt5.4.2/5.4/mingw491_32/qml/Material/PapyrosExtensions:1:1: module "Papyros.Material" is not installed
file:///C:/Qt/Qt5.4.2/5.4/mingw491_32/qml/Material/Toolbar.qml:73: TypeError: Cannot read property 'color' of undefined
file:///C:/Qt/Qt5.4.2/5.4/mingw491_32/qml/Material/Toolbar.qml:127: TypeError: Cannot read property 'rightSidebar' of undefined
file:///C:/Qt/Qt5.4.2/5.4/mingw491_32/qml/Material/Toolbar.qml:166: TypeError: Cannot read property 'rightSidebar' of undefined

**Comment by ricardomv** [comment]
You need to provide more information, what code are you trying to run what issue do you see, what version of Qt and qml-material are you using and what is the desired behavior.

**Comment by iBelieve** [comment]
@lixiang19870818 Is this still an issue? If so, please provide the smallest possible sample code that reproduces this error.

**Comment by iBelieve** [comment]
Closing to due lack of response from OP. Please reopen if this is still an issue.
