### ISSUE TITLE
Normalize ApplicationWindow setup

### ISSUE THREAD

**Issue by geiseri** [papyros/qml-material#37]
Right now there is very tight coupling between the ApplicationWindow, Toolbar, PageStack, Page and ActionBar.  They reference items that may or may not be declared yet, and depending on how the application is started you can get hangs or null errors.  Normally QML will want as much statically declared, and things that are dynamic are created via delegates or Loaders.  The Page container has quite a few data elements (actions, tabs, transitions) that should really be exposed as models, and the PageStack uses delegates to render those models when they change.  This will ensure everything is correctly set up before the bindings are hooked up.

I think the Page should really become an Object container with the actionbar, title and content properties.  Then the PageStack would have a delegate that allows it to render the current item based on the index that is manipulated by push and pop..

**Comment by iBeliever** [comment]
We've come a long way since this was opened. We've migrated to using QtQuick.Controls, which has been a huge benefit for cleaning up the code. Most of the tight coupling should have been addressed. If there are any further concerns, please reopen this or open issues for specific things. Thanks!
