### ISSUE TITLE
Make error 

### ISSUE THREAD

**Issue by ctnlaring** [papyros/qml-material#377]
I'm on Fedora 23 Workstation
$qmake-qt5
$ make
cd modules/Material/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/Collin/Papyros/qml-material/modules/Material/Material.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/Collin/Papyros/qml-material/modules/Material'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/Collin/Papyros/qml-material/modules/Material'
cd modules/Material/Extras/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/Collin/Papyros/qml-material/modules/Material/Extras/Extras.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/Collin/Papyros/qml-material/modules/Material/Extras'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/Collin/Papyros/qml-material/modules/Material/Extras'
cd modules/QtQuick/Controls/Styles/Material/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/Collin/Papyros/qml-material/modules/QtQuick/Controls/Styles/Material/Material.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/Collin/Papyros/qml-material/modules/QtQuick/Controls/Styles/Material'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/Collin/Papyros/qml-material/modules/QtQuick/Controls/Styles/Material'
cd tests/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/Collin/Papyros/qml-material/tests/tests.pro -o Makefile ) && make -f Makefile 
Project ERROR: Unknown module(s) in QT: qml qmltest
Makefile:120: recipe for target 'sub-tests-make_first' failed
make: **\* [sub-tests-make_first] Error 3

**Comment by iBelieve** [comment]
You need the Qt5Test and Qt5QuickTest QML modules. I don't know what packages provide them on Fedora, you'll have to search your package archives or ask in Fedora-specific channels.
