### ISSUE TITLE
qml/Material/PapyrosExtensions:1:1:"Papyros.Material" is not installed 

### ISSUE THREAD

**Issue by lixiang19870818** [papyros/qml-material#378]
ERRO: qml/Material/PlatformExtensions.qml:43: Error: Qt.createQmlObject(): failed to create object:

platformExtensions = Qt.createQmlObject('import Papyros.Material 0.1; PlatformExtensions {}',
                platform, "PapyrosExtensions");
PlatformExtensions.qml  is the file in qml-material;
ERRO:"qml/Material/PapyrosExtensions:1:1: module "Papyros.Material" is not installed。"
Could you tell me how to solve this?
##

**Comment by aldonin** [comment]
Seems like  [duplicate](https://github.com/papyros/qml-material/issues/351)?

**Comment by iBelieve** [comment]
@lixiang19870818 What branch/commit are you running? This should have been fixed already.

**Comment by iBelieve** [comment]
Closing to due lack of response from OP. Please reopen if this is still an issue.
