### ISSUE TITLE
Various components unavailable 

### ISSUE THREAD

**Issue by ctnlaring** [papyros/qml-material#379]
This is when trying to run liri player
QQmlApplicationEngine failed to load component
qrc:/qml/BaseApplication.qml:17 Type PlayerWindow unavailable
qrc:/qml/PlayerWindow.qml:8 Type Page unavailable
file:///usr/lib64/qt5/qml/Material/Page.qml:231 Type ActionBar unavailable
file:///usr/lib64/qt5/qml/Material/ActionBar.qml:214 Type IconButton unavailable
file:///usr/lib64/qt5/qml/Material/IconButton.qml:81 Type Tooltip unavailable
file:///usr/lib64/qt5/qml/Material/Tooltip.qml:37 Type Popover unavailable
file:///usr/lib64/qt5/qml/Material/Popover.qml:105 Type View unavailable
file:///usr/lib64/qt5/qml/Material/View.qml:19 module "QtGraphicalEffects" is not installed

**Comment by marco-piccolino** [comment]
looks like you are missing QtGraphicalEffects, which is part of the Qt
distribution

2016-01-27 4:20 GMT+01:00 Collin Norwood notifications@github.com:

**Comment by ctnlaring** [comment]
@marco-piccolino I needed that and had to update import statements to Material 0.2
