### ISSUE TITLE
Take advantage of the new HiDPI support coming in Qt 5.6

### ISSUE THREAD

**Issue by iBelieve** [papyros/qml-material#380]
https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/
##

**Comment by ricardomv** [comment]
Can this replace the Units.dp() method?

**Comment by iBelieve** [comment]
@ricardomv Hopefully. It depends on if one Material dp is equivalent to one Qt point. If not, Units.dp() would just be a simple multipler for easy use of Material dps.
