### ISSUE TITLE
Missing my_library_music.svg

### ISSUE THREAD

**Issue by ctnlaring** [papyros/qml-material#381]
I get:
`file:///usr/lib64/qt5/qml/Material/Icon.qml:63:5: QML Image: Cannot open: file:///usr/lib64/qt5/qml/Material/icons/av/my_library_music.svg`
##

**Comment by iBelieve** [comment]
Is this an error in the demo or your own project? We're doing away with including all the icons in #396. After that gets merged, you'll use an `icons.yml` file to list all the icons you want included in your project.
