### ISSUE TITLE
Option for non-system-wide installation

### ISSUE THREAD

**Issue by jmc-figueira** [papyros/qml-material#386]
From what I could follow from recent changes, the build system has been changed to CMake and the installation is now system-wide. While I agree you had your very good reasons for doing it, I don't particularly enjoy the idea of having a qml library installed system-wide when Qt itself is not (on OS X, I might add). Is there an alternative way to install or will I have to compromise on this one?

**Comment by marco-piccolino** [comment]
there's a pull request waiting to be merged: https://github.com/papyros/qml-material/pull/375

**Comment by iBelieve** [comment]
CMake really isn't any different than QMake in terms of installing system-wide. You can install to per-user directories as well (in fact, that's how I develop and test on Linux). Anyway, the pull request @marco-piccolino  has been merged, so you can use that way as well.

Are you wanting to install the library to a folder somewhere in your user directory or just use it directly from the project folder?

**Comment by jmc-figueira** [comment]
I intended to install it to the Qt installation folder, or a subfolder of that, most precisely, which in my system is located in /Users/joao/Documents/Qt/5.5

**Comment by iBelieve** [comment]
@jmc-figueira CMake lets you do that quite easily.

This should work:

```
cmake .. -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
```

If it doesn't, you can specifically choose the install path like:

```
cmake .. -DQML_INSTALL_DIR=/path/to/qml/modules/dir
```

**Comment by jmc-figueira** [comment]
Alright, I may need to find a way to install ECM though, as it is a requirement.

**Comment by jmc-figueira** [comment]
Alright, I managed to install it successfully in the directory I intended, seems to be working fine. Thank you for the help!
