### ISSUE TITLE
How to use qml-material in pyqt5?

### ISSUE THREAD

**Issue by hollow97** [papyros/qml-material#388]
i make it  and demo can run successfully by (qmlscene main.qml ),but i use pyqt5,it can't run .
hwj.qml:2:1: module "Material" is not installed 
     import Material 0.2 
     ^
who can help me?

**Comment by ghost** [comment]
You can copy the two folders inside qml-material/modules in your site-packages/PyQt5/qml.

**Comment by hollow97** [comment]
@geoffrey198  i try it ,but it isn't usefull and It still report that error.i work it  in linux.

**Comment by iBelieve** [comment]
I'm not familiar with PyQt, but it should be as simple as installing the contents modules directory wherever your PyQt installation is looking for modules. If that doesn't work, you could try asking in PyQt support channels or in our Gitter channel (linked from the README).
