### ISSUE TITLE
Add some examples

### ISSUE THREAD

**Issue by iBeliever** [papyros/qml-material#4]
Add some examples of how the toolkit can be used.

**Comment by cgafeng** [comment]
I newbie for the qml, how to install this on windows?

**Comment by nimaim** [comment]
cgafeng,I just tested this today so I'll see if I can guide you in the right direction. First step is to clone the qml-extras repo and install the modules there (qmake, make, make install). Use Qt Creator and its internal toolchain to do this. Next, clone qml-material and do the same (qmake, make, make install). Check to see if you have the Material modules in <Qt root dir>/Qt version/gcc/qml (or whatever compiler you are using; for Windows this will probably be called mingw). Now close and reopen Qt Creator so it can find the Material imports. Now if you want to test it, open up main.qml in /demo and go to Tools ... External ... Qt Quick ... Qt Quick 2 Preview (QML Scene). You should see a test program of all the Material controls. 

Building and running qml-materials.pro should run internal tests that will look like this:

********* Start testing of materials *********
Config: Using QtTest library 5.4.0, Qt 5.4.0 (i386-little_endian-ilp32 shared (dynamic) release build; by GCC 4.6.1)
PASS   : materials::Card Test::initTestCase()
PASS   : materials::Card Test::test_showCard()
PASS   : materials::Card Test::cleanupTestCase()
PASS   : materials::PageStack Test::initTestCase()
QDEBUG : materials::PageStack Test::test_showCard() qml: here
PASS   : materials::PageStack Test::test_showCard()
PASS   : materials::PageStack Test::cleanupTestCase()
Totals: 6 passed, 0 failed, 0 skipped, 0 blacklisted
********* Finished testing of materials *********
Press <RETURN> to close this window...

Hope this helps.

**Comment by ricardomv** [comment]
we now have a working demo with examples for the library and documentation can be generated with qdoc
