### ISSUE TITLE
NavigationDrawer icon menu.svg missing

### ISSUE THREAD

**Issue by majuca** [papyros/qml-material#404]
Hi, when I start the demo, it's ok but when I implemented in my application, I have  

QML Image: Cannot open: qrc:/icons/navigation/menu.svg

**Comment by marco-piccolino** [comment]
You need to add it yourself in the icons.yml file and run the python script
to download icons and generate qrc. Take a look at the demo. This is not
well documented yet. I think this icon should be put as core tho.
Il 06 apr 2016 9:19 PM, "Jean-Luc Gyger" notifications@github.com ha
scritto:

**Comment by majuca** [comment]
It works, thank you

**Comment by iBelieve** [comment]
I'll add documentation for `icons.yml` and add the icon to the core icons this evening after work. Thanks for reporting this!
