### ISSUE TITLE
demo.qrc

### ISSUE THREAD

**Issue by majuca** [papyros/qml-material#406]
Hi,

There is icons/navigation_menu.svg' in demo.qrc but the file doesn't exist anymore

**Comment by geiseri** [comment]
+1 breaks packaging.

**Comment by MaxMansfield** [comment]
+1

**Comment by luntik2012** [comment]
cp QML_MATERIAL_DIR{,/demo}/icons/navigation_menu.svg

**Comment by iBelieve** [comment]
This has now been fixed.
