### ISSUE TITLE
Window make-install error

### ISSUE THREAD

**Issue by hezhongfeng** [papyros/qml-material#418]
I tested 2013、2015 and mingw32
"sed"error 
It's not a command,so it stoped
so the qmldir is empty
I copy the src's qmldir into the dir material,it doesn't work yet
and so I couldn't run  it

**Comment by malwoden** [comment]
As a work around, if you have git for windows installed (which includes sed) you can add the directory which contains sed to your path and the install will work, something like

`set PATH=%PATH%;C:\Program Files\Git\usr\bin`

then `make install`

**Comment by hezhongfeng** [comment]
@malwoden Thank you your answer,I will try.

**Comment by hezhongfeng** [comment]
@malwoden It's ok,thank you.
