### ISSUE TITLE
Expose the `MaterialRegisterHelper`

### ISSUE THREAD

**Issue by itay-grudev** [papyros/qml-material#436]
I am using `qml-materials` via a git submodule. Everything is fine except for the fact that the `Units` and `Device` types are not available. This could easily be fixed by manually registering them, but as you have a utility that does it (`MaterialRegisterHelper`) why not expose it so it could be used directly.

**Comment by oKcerG** [comment]
You can define `QPM_INIT` so a static `MaterialRegisterHelper` can be instancied

**Comment by itay-grudev** [comment]
Oh that's neat. Thanks!
