### ISSUE TITLE
Units.dp and dp() function always gives the same value.

### ISSUE THREAD

**Issue by arif193** [papyros/qml-material#448]
i don't know if papyros handle qml-material for device screen yet, but it seems like that this issue is related to Qml core module after all, the Units.dp property and the dp() function always gives the same value = 1 for many screen types(xxhdpi, hdpi and so on..... ) , i wonder to know if anyone had already found a solution, and how, for me i've already tried to find if there is another type i can used but with no success, until now i've found one trick (i may call it a dirty one !) is by estimating the dp density using the height of the actual toolbar on the android phone, since it always equal to 24*dp, then divided it by 24, and using the new value to scale others elements to fit on the screen.

**Comment by remi-parain** [comment]
I created a pull request some time ago which manage to resolve this issue on android.
here is the  commit : 
https://github.com/papyros/qml-material/pull/400/commits/ce84b7f4437b199069d4d9c600c61ccc43d25435

it resolved all my issues :)

**Comment by arif193** [comment]
you saved my time thanks
i'm curiously wonder why it didn't get merged yet

**Comment by iBelieve** [comment]
@remi-parain's pull request has been merged, so this should be fixed now.
