### ISSUE TITLE
Wrong density in Android Devices

### ISSUE THREAD

**Issue by leonardo2d** [papyros/qml-material#45]
Hi. I've successfully compiled and deployed the example qml on a LG Nexus 4. Screen density looks wrong, though. Device resolution is 768x1280. See attached screenshots.

![screenshot_2014-12-15-01-25-12](https://cloud.githubusercontent.com/assets/945210/5430535/6ca14af8-83f9-11e4-9ded-a47cb63afa62.png)
![screenshot_2014-12-15-01-25-18](https://cloud.githubusercontent.com/assets/945210/5430536/78b56c34-83f9-11e4-8fc6-67f67f27ab0e.png)

**Comment by benlau** [comment]
Why it don't just detect the DP value from Android OS directly? or Android is not supposed to be supported in this project?

**Comment by boghison** [comment]
@benlau There's a simple calculation involved and that's what we're doing. The bug/do branch works perfectly on Android devices.

**Comment by leonardo2d** [comment]
I can confirm that this issue is fixed.

**Comment by iBeliever** [comment]
Great, thanks for testing @leonardo2d.
