### ISSUE TITLE
About system status bar

### ISSUE THREAD

**Issue by QShen3** [papyros/qml-material#453]
Few days ago, one of my friends suggested me that my Android app should have Immersive status bar. It was written by Qt Quick with qml-material. I accepted the suggestion and tried to use Google's API to do it. And I got this:

![image](https://cloud.githubusercontent.com/assets/3995336/16168747/3aa25010-3546-11e6-9075-e89f06ff9fcb.png)

An unhappy result...

Because Qt apps doesn't use the Android's layout, whether you have set the layout property _fitsSystemWindows_ to true is useless.

In order to solve this problem, I add a property _statusBarHeight_ to Toolbar to set the action bar height and transfer it to page's action bar.

Toolbar.qml:

```
property int statusBarHeight: 0

property int actionBarHeight: {
        if (!page || page.actionBar.hidden)
            return 0

        var height = implicitHeight + page.actionBar.extendedHeight + statusBarHeight

        if (page.rightSidebar && page.rightSidebar.showing) {
            var sidebarHeight = implicitHeight + page.rightSidebar.actionBar.extendedHeight + statusBarHeight

            height = Math.max(height, sidebarHeight)
        }

        return height
    }
function push(page) {
        stack.push(page.actionBar)

        page.actionBar.toolbar = toolbar
        page.actionBar.statusBarHeight = statusBarHeight;
        toolbar.page = page

        if (page.rightSidebar && page.rightSidebar.actionBar)
            rightSidebarStack.push(page.rightSidebar.actionBar)
        else
            rightSidebarStack.push(emptyRightSidebar)
    }
......
```

And in Action bar, I changed the actionRow's anchors.

ActionBar.qml:

```
Row {
        id: actionsRow

        anchors {
            top: parent.top;
            topMargin: statusBarHeight;
            right: parent.right
            rightMargin: Units.dp(16)
        }
......
}
```

Then, the property statusBarHeight in Toolbar was transferred from ApplicationWindow. So I just need to set this property to the system status bar height in ApplicationWindow

```
ApplicationWindow{
......
    statusBarHeight: utility.getStatusBarHeight();
......
}
```

Finally, It looked like this:

![qq 20160618115825](https://cloud.githubusercontent.com/assets/3995336/16169015/393aa38a-3550-11e6-9935-a925bb7ac245.png)

Beside Andorid, IOS and Win10 mobile also have Immersive status bar, so I hope it can be added into qml-material.

**Comment by SunRain** [comment]
I think you should make pr instead of opening issue lol
