### ISSUE TITLE
System-wide installation failed

### ISSUE THREAD

**Issue by afendin** [papyros/qml-material#469]
mingw32-make[2]: **\* [install_qmldir] Error 1
mingw32-make[2]: Leaving directory 'D:/Projects/Megamart/material/build/src'
Makefile:44: recipe for target 'release-install' failed
mingw32-make[1]: **\* [release-install] Error 2
mingw32-make[1]: Leaving directory 'D:/Projects/Megamart/material/build/src'
Makefile:52: recipe for target 'sub-src-install_subtargets' failed
mingw32-make: **\* [sub-src-install_subtargets] Error 2

**Comment by SuperChrisliu** [comment]
did you solve that problem?
