### ISSUE TITLE
Can't run the demo from the qml-material repo

### ISSUE THREAD

**Issue by kgupta15** [papyros/qml-material#476]
Hi, 
I am on Ubuntu 14.04 Qt v5.7. I am trying to run the demo provided in the QML-Material repository. The error I get is: 

```
QQmlApplicationEngine failed to load component
qrc:/main.qml:2 module "Material" is not installed
qrc:/main.qml:3 module "Material.ListItems" is not installed
qrc:/main.qml:2 module "Material" is not installed
qrc:/main.qml:3 module "Material.ListItems" is not installed
```

I tried adding this line in `main.cpp`:
`engine.addImportPath("qrc:///");`
But, it didn't help in removing the error (It didnt have any visible effect).
What should I do to make the demo run?

**Comment by codimension** [comment]
Hi daemonSlayer, have you built and installed qml-material yet? I can recreate the problem you're having by trying to run the demo before installing the qml-material.

After following the instructions for a global install, running the demo succeeds for me. Could you post the steps you took before running the demo?

Thanks!

**Comment by kgupta15** [comment]
I hadn't installed the qml-material beforehand as I have been using it as a submodule, downloading and directly using! How do I install it ? I don't have qmake installed as the qt I have is installed using the .run file and not the Ubuntu provided one.

**Comment by benlau** [comment]
To get the demo program works, you may try to apply following changes:

https://github.com/benlau/qml-material/commit/a45754bd1c7cb9d47aa378c793104c1abe570c09
