### ISSUE TITLE
Density problem for low desktop resolutions

### ISSUE THREAD

**Issue by mhammerc** [papyros/qml-material#53]
Hi everyone :)
I've two screens : 1920x1080 and 1360x768.
All work fine on 1920x1080 but the text is very very very little and unreadable on 1360x768.
First image is on high resolution and the second on the lower resolution.
I thinks the problem come from units.dp, no ?
![High resolution](http://uplmg.com/data/highres.png)
![Low resolution](http://uplmg.com/data/lowres.png)

**Comment by Imote** [comment]
I just noticed that the problem still exists

**Comment by boghison** [comment]
@Imote You can just customize it, the same way you did before :)

**Comment by Imote** [comment]
Yes i just did it. Now it's ultra big on my big screen and it appear to be good and my lower screen :( :p !

**Comment by Imote** [comment]
I've fixed the value of pixelDensity to 4 and the multiplier to 1.4. Now, it work on both screens without problems :)
