### ISSUE TITLE
Floating Action Button component

### ISSUE THREAD

**Issue by ricardomv** [papyros/qml-material#56]
http://www.google.com/design/spec/components/buttons.html#buttons-floating-action-button

@iBeliever how are you thinking on implementing this one since we can't clip on a rounded rectangle (circle)?
I have been looking at options and i think the better one is to implement clipping in c++.
But i don't know how to do it.

**Comment by iBeliever** [comment]
We now have an action button and the ink is properly clipped too! I've added it to the Button demo as well.
