### ISSUE TITLE
Install on Ubuntu 14.04

### ISSUE THREAD

**Issue by danielsanfr** [papyros/qml-material#65]
Sorry if any inconvenience this question.

I am trying to install it on Ubuntu, but as I can only install Qt 5.3+ from the binary provided in [qt.io](qt.io) I'm not able to install it.

Could someone help me with this installation?

I've tried to do this:

    $ ./<PAHT_TO_QT_DIR>/Qt5.4.0/5.4/gcc_64/bin/qmake PATH_TO_QML_EXTRAS>/qml-extras/qml-extras.pro
    $ make check
    $ make install
    $ ./<PAHT_TO_QT_DIR>/Qt5.4.0/5.4/gcc_64/bin/qmake <PATH_TO_QML_MATERIAL>/qml-material/qml-materials.pro
    $ make
    $ make check # Optional, make sure everything is working correctly
    $ sudo make install

But on `make check` of the `qml-extras` occurs some errors.

**Comment by boghison** [comment]
@danielsanfr What issues are you getting exactly? I've cloned the repo anew, ran make check and it didn't show any errors.

**Comment by danielsanfr** [comment]
Thank you very much @boghison. I've cloned the repo anew and work now!
Maybe it was something they did now, but now work for me.

One more thing, as this is a work in progress, I would like to know if there is a way to test this demo application without having to install all this always.

Since I imagine that whenever I would have upgraded to redo these steps to see the changes, correct?

**Comment by boghison** [comment]
@danielsanfr Well, yes this is a WIP. Right now i.e. at this commit/point in time, the git version works fine. You could even try building a few apps with it. Since there aren't so many bugs, what you should expect is new components and features, but to answer your question, yes, to see the changes you will have to pull from the repo once in a while (I am pretty sure you could write a script to automate this, if you think this is a painful process)

**Comment by danielsanfr** [comment]
Right. What I was wondering is whether it would be possible (at least for now), be necessary only use `git clone` and already use changes in a demo application.

I'll try to do this in a small fork just to illustrate my idea.

**Comment by boghison** [comment]
@danielsanfr What do you mean by that? I am afraid I don't understand.

**Comment by ElmoRapz** [comment]
I think he was saying that he could use git clone command to get and have it to where it runs the OS on a type of virtual machine to see if the changes were effective or not.
At least that's what I was getting from his comment

**Comment by iBeliever** [comment]
I think what he wants is a way to run the demo without having to install the framework. Actually, that's already possible, as the demo `qmlproject` file locally imports the module, without requiring it to be installed. You could of course do the same from the command line using `qmlscene -I ../modules main.qml`.

**Comment by danielsanfr** [comment]
@iBeliever that's exactly what I would!

I have only one doubt, and the dependence with the qml-extras?

If it really works, it would be good that someone would add this information to the README.

**Comment by iBeliever** [comment]
@danielsanfr No, the dependency is not set up for qml-extras (we wouldn't know where you would download it relative to qml-material). But it's easy enough to modify the qmlproject file or change the args passed to qmlscene.

**Comment by iBeliever** [comment]
Closing now as I believe the original issue has now been addressed.
