### ISSUE TITLE
Pushing multiple pages to stack at once

### ISSUE THREAD

**Issue by nathanhourt** [papyros/qml-material#67]
This may already be possible and I'm just not seeing how (I see the PageStack pushFrom method, but I can't tell what it's for exactly), but it would be useful to be able to push several pages at once and only have one transition to the new top page (same as passing an array to http://doc.qt.io/qt-5/qml-qtquick-controls-stackview.html#push-method).

**Comment by iBeliever** [comment]
We're now using the StackView from QtQuick.Controls, so we support whatever they support.
