### ISSUE TITLE
Double-clicking back button on second page in stack puts app in inconsistent state

### ISSUE THREAD

**Issue by nathanhourt** [papyros/qml-material#70]
Create a simple app which pushes a second page to the pageStack, then double click the back button. This pops twice and leaves the app unusable (in my real app, it actually crashes; in the simple demo below, it just leaves the UI empty).

Demo:
```
import QtQuick 2.2
import Material 0.1
import Material.ListItems 0.1 as ListItem

ApplicationWindow {
   id: demo
   
   theme {
      accentColor: "#009688"
   }
   
   initialPage: page
   
   Page {
      id: page
      
      title: "Component Demo"
      
      Button {
         anchors.centerIn: parent
         text: "Push"
         onClicked: pageStack.push(c)
      }
      
      
   }
   Component {
      id: c
      Page {
        title: "Page 2"
      }
   }
}
```

Push the button, then double click the back button.

**Comment by nimaim** [comment]
With iBeliever's recent conversion of the page stack functions to use the native stackview in QtQuick (https://github.com/papyros/qml-material/commit/999cbf9579a1632fec94e1108395b64ff29c68dc), this may be fixed. It seems to always double pop for me with a double click as well (agree, it shouldn't), but it never leaves the app in an unusable state for me.

**Comment by nathanhourt** [comment]
The StackView will prevent popping the bottom item off the stack, which is why you're no longer seeing an unusable state. This addresses the primary concern, but it is still (I think) undesirable behavior and should be fixed. Some apps may not want to allow this behavior, for instance an app which has three pages on the stack, with some page at the bottom, a second page with the back button disabled (for whatever reason, maybe it's a modal dialog or ad screen or whatever it be) and a third page with a back button again. The app should not allow the user to navigate directly back to the base page, yet it would be possible to do so by double-tapping the back button.

On the other hand, the double-tap may be desirable, if the user wants to quickly navigate back to the base page (and it's legal to do so). So I think the correct behavior is to allow double-tapping iff the page being transitioned to has its back button enabled. It would be worth checking if the middle page is ever Active if this happens, though, as the application may run some code when the middle page is Active and skipping that step could break things.

**Comment by iBeliever** [comment]
I've fixed this so you can't double tap and go back multiple pages. Any confusion caused by that unintentionally invoking behavior isn't worth the ability to quickly jump back multiple pages.
