### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Madeby-T** [papyros/qml-material#75]
how i can install the material design on win7 , or Ubuntu 14.10??

**Comment by ilnuribat** [comment]
https://github.com/papyros/qml-material/issues/73
https://github.com/papyros/qml-material/issues/65

**Comment by Madeby-T** [comment]
thank you,but I already see it, I don't undestand, so can you explain me?

**Comment by Madeby-T** [comment]
???

**Comment by iBeliever** [comment]
Support questions aren't really appropriate for filing as GitHub issues unless you're familiar with what you're doing and know there is a bug in our code. Please come to our IRC channel `#papyros` on Freenode and I can try to help you through getting it set up. My IRC nick is `iBelieve`. Thanks!
