### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by mottosso** [papyros/qml-material#92]
Hi Papyros!

Would it be possible to reach out to you via something like [Gitter](https://gitter.im) or similar for basic questions and help?

I'm running a [small open source project](https://gitter.im/abstractfactory/pyblish) too and have it very useful in getting people started and keeping in touch with how it is being used.

In this case, I just cloned this (absolutely wonderful!) repository and was playing around with the demos, but are having some issues that I'm sure relates to some basic misunderstanding of how to use it properly and so it would be great to be able to post quick questions somewhere.

If you would rather I open up issues, I'd be happy to do so instead.

Thanks,
Marcus

**Comment by marco-piccolino** [comment]
Here you go. Thanks @iBeliever 

https://gitter.im/papyros/qml-material
